#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Avatar1

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass ABP_Avatar1.ABP_Avatar1_C
// 0x03B0 (0x0670 - 0x02C0)
class UABP_Avatar1_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x02C8(0x0048)()
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0310(0x0060)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0370(0x00D8)()
	struct FAnimNode_StateResult                  AnimGraphNode_StateResult;                         // 0x0448(0x0048)()
	struct FAnimNode_StateMachine                 AnimGraphNode_StateMachine;                        // 0x0490(0x0108)()
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x0598(0x00D8)()

public:
	void ExecuteUbergraph_ABP_Avatar1(int32 EntryPoint);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ABP_Avatar1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ABP_Avatar1_C")
	}
	static class UABP_Avatar1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UABP_Avatar1_C>();
	}
};
DUMPER7_ASSERTS_UABP_Avatar1_C;

SDK_NAMESPACE_END
