#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AvatarSubSystem

#include "Basic.hpp"

#include "NRC_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AvatarSubSystem.BP_AvatarSubSystem_C
// 0x0000 (0x0320 - 0x0320)
class UBP_AvatarSubSystem_C final : public UAvatarSubsystem
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AvatarSubSystem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AvatarSubSystem_C")
	}
	static class UBP_AvatarSubSystem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AvatarSubSystem_C>();
	}
};
DUMPER7_ASSERTS_UBP_AvatarSubSystem_C;

SDK_NAMESPACE_END
