#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy

#include "Basic.hpp"

#include "BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_classes.hpp"
#include "BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy.BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C.ExecuteUbergraph_BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C::ExecuteUbergraph_BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C", "ExecuteUbergraph_BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy");

	Params::BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C_ExecuteUbergraph_BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy.BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C.ClickFun
// (Native, Event, Public, BlueprintEvent)
// Parameters:
// const class FString&                    URL                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UBP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C::ClickFun(const class FString& URL)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C", "ClickFun");

	Params::BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C_ClickFun Parms{};

	Parms.URL = std::move(URL);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy.BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UBP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C", "GetModuleName");

	Params::BP_RichTextUnderlineAndLinkDecorator_SystemSettingPrivacy_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
