#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CrashReport

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CrashReport_structs.hpp"


SDK_NAMESPACE_START

// Class CrashReport.CrashReportBlueprintLibrary
// 0x0000 (0x0028 - 0x0028)
class UCrashReportBlueprintLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void UpdateGameDebugData(EGameDebugDataType GameDebugType, const class FString& Data);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("CrashReportBlueprintLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CrashReportBlueprintLibrary")
	}
	static class UCrashReportBlueprintLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCrashReportBlueprintLibrary>();
	}
};
DUMPER7_ASSERTS_UCrashReportBlueprintLibrary;

SDK_NAMESPACE_END
