#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CrashReport

#include "Basic.hpp"

#include "CrashReport_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function CrashReport.CrashReportBlueprintLibrary.UpdateGameDebugData
// 0x0018 (0x0018 - 0x0000)
struct CrashReportBlueprintLibrary_UpdateGameDebugData final
{
public:
	EGameDebugDataType                            GameDebugType;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Data;                                              // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CrashReportBlueprintLibrary_UpdateGameDebugData;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
