#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CustomShadow

#include "Basic.hpp"

#include "CustomShadow_classes.hpp"
#include "CustomShadow_parameters.hpp"


SDK_NAMESPACE_START

// Function CustomShadow.CustomShadowComponent.SetUseAmbientShadow
// (Final, Native, Public)
// Parameters:
// bool                                    NewUseAmbientShadow                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UCustomShadowComponent::SetUseAmbientShadow(bool NewUseAmbientShadow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CustomShadowComponent", "SetUseAmbientShadow");

	Params::CustomShadowComponent_SetUseAmbientShadow Parms{};

	Parms.NewUseAmbientShadow = NewUseAmbientShadow;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
