#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CustomShadow

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function CustomShadow.CustomShadowComponent.SetUseAmbientShadow
// 0x0001 (0x0001 - 0x0000)
struct CustomShadowComponent_SetUseAmbientShadow final
{
public:
	bool                                          NewUseAmbientShadow;                               // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CustomShadowComponent_SetUseAmbientShadow;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
