#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FalconCore

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class FalconCore.FalconTXTUtil
// 0x0000 (0x0028 - 0x0028)
class UFalconTXTUtil final : public UBlueprintFunctionLibrary
{
public:
	static bool AppendTXT(const class FString& InPath, const class FString& InText);
	static class FString LoadTXT(const class FString& InPath);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FalconTXTUtil")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FalconTXTUtil")
	}
	static class UFalconTXTUtil* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFalconTXTUtil>();
	}
};
DUMPER7_ASSERTS_UFalconTXTUtil;

SDK_NAMESPACE_END
