#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameJoyPlugin

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.CheckAlbumVideoExist
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_CheckAlbumVideoExist final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_CheckAlbumVideoExist;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.CheckSDKPermission
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_CheckSDKPermission final
{
public:
	class FString                                 Type;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_CheckSDKPermission;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.ClipVideo
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_ClipVideo final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 videoEditJson;                                     // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_ClipVideo;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.CloseFd
// 0x0008 (0x0008 - 0x0000)
struct BP_GameJoyPluginLibrary_CloseFd final
{
public:
	int32                                         fd;                                                // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_CloseFd;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.DeleteVideoByAlbum
// 0x0028 (0x0028 - 0x0000)
struct BP_GameJoyPluginLibrary_DeleteVideoByAlbum final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 albumName;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 srcPath;                                           // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_DeleteVideoByAlbum;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.EnableBgmMix
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_EnableBgmMix final
{
public:
	bool                                          mixing;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_EnableBgmMix;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.EnableInGameAudio
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_EnableInGameAudio final
{
public:
	bool                                          enable;                                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_EnableInGameAudio;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GenerateMomentsVideo
// 0x0010 (0x0010 - 0x0000)
struct BP_GameJoyPluginLibrary_GenerateMomentsVideo final
{
public:
	class FString                                 videoTimeStampListJson;                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GenerateMomentsVideo;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GenerateVideoCover
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_GenerateVideoCover final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 videopath;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GenerateVideoCover;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetCaptureSource
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_GetCaptureSource final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetCaptureSource;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetDeviceInfo
// 0x0010 (0x0010 - 0x0000)
struct BP_GameJoyPluginLibrary_GetDeviceInfo final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetDeviceInfo;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetFdFromUri
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_GetFdFromUri final
{
public:
	class FString                                 Uri;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetFdFromUri;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetFilePathFromUri
// 0x0020 (0x0020 - 0x0000)
struct BP_GameJoyPluginLibrary_GetFilePathFromUri final
{
public:
	class FString                                 uriPath;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetFilePathFromUri;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetFilesFromPath
// 0x0020 (0x0020 - 0x0000)
struct BP_GameJoyPluginLibrary_GetFilesFromPath final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Path;                                              // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          isIncludeChildren;                                 // 0x0018(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetFilesFromPath;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetFilesInDir
// 0x0020 (0x0020 - 0x0000)
struct BP_GameJoyPluginLibrary_GetFilesInDir final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetFilesInDir;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetFreeDiskSpace
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_GetFreeDiskSpace final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetFreeDiskSpace;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetGFilePathBase
// 0x0010 (0x0010 - 0x0000)
struct BP_GameJoyPluginLibrary_GetGFilePathBase final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetGFilePathBase;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetInstance
// 0x0008 (0x0008 - 0x0000)
struct BP_GameJoyPluginLibrary_GetInstance final
{
public:
	class UBP_GameJoyPluginLibrary*               ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetInstance;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetPathRelativeTo
// 0x0030 (0x0030 - 0x0000)
struct BP_GameJoyPluginLibrary_GetPathRelativeTo final
{
public:
	class FString                                 fromPath;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RelativeTo;                                        // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0020(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetPathRelativeTo;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetPaths
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_GetPaths final
{
public:
	int32                                         pathType;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          relative;                                          // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ReturnValue;                                       // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetPaths;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetRecorderPosition
// 0x0010 (0x0010 - 0x0000)
struct BP_GameJoyPluginLibrary_GetRecorderPosition final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetRecorderPosition;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetSandboxPath
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_GetSandboxPath final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetSandboxPath;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetTimeMilliSeconds
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_GetTimeMilliSeconds final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetTimeMilliSeconds;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetTimeSeconds
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_GetTimeSeconds final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetTimeSeconds;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetVideoInfo
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_GetVideoInfo final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 videoPathJson;                                     // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetVideoInfo;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.GetVideoMd5
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_GetVideoMd5 final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 videoPathJson;                                     // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_GetVideoMd5;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.IsDirExist
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_IsDirExist final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_IsDirExist;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.IsFileExist
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_IsFileExist final
{
public:
	class FString                                 FilePath;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_IsFileExist;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.IsIOSFileExist
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_IsIOSFileExist final
{
public:
	class FString                                 FilePath;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_IsIOSFileExist;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.IsRecorderDialogShow
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_IsRecorderDialogShow final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_IsRecorderDialogShow;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.IsRecording
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_IsRecording final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_IsRecording;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.MergeVideoWithImageAndVideo
// 0x0038 (0x0038 - 0x0000)
struct BP_GameJoyPluginLibrary_MergeVideoWithImageAndVideo final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 videopath;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 headerVideo;                                       // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ImagePath;                                         // 0x0028(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_MergeVideoWithImageAndVideo;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.MoveAlbumToLocal
// 0x0028 (0x0028 - 0x0000)
struct BP_GameJoyPluginLibrary_MoveAlbumToLocal final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 albumPath;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 localPath;                                         // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_MoveAlbumToLocal;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.MoveFile
// 0x0028 (0x0028 - 0x0000)
struct BP_GameJoyPluginLibrary_MoveFile final
{
public:
	class FString                                 From;                                              // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 dst;                                               // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_MoveFile;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.MoveFileToDocument
// 0x0020 (0x0020 - 0x0000)
struct BP_GameJoyPluginLibrary_MoveFileToDocument final
{
public:
	class FString                                 fromPath;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 toSubPath;                                         // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_MoveFileToDocument;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.MoveVideoToAlbum
// 0x0028 (0x0028 - 0x0000)
struct BP_GameJoyPluginLibrary_MoveVideoToAlbum final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 albumName;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 srcPath;                                           // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_MoveVideoToAlbum;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.PxAuthGetSdkVersion
// 0x0010 (0x0010 - 0x0000)
struct BP_GameJoyPluginLibrary_PxAuthGetSdkVersion final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_PxAuthGetSdkVersion;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.PxAuthSetSecretKey
// 0x0010 (0x0010 - 0x0000)
struct BP_GameJoyPluginLibrary_PxAuthSetSecretKey final
{
public:
	class FString                                 SecretKey;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_PxAuthSetSecretKey;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.RequestSDKPermission
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_RequestSDKPermission final
{
public:
	int32                                         EventId;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Type;                                              // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_RequestSDKPermission;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetAlbumName
// 0x0010 (0x0010 - 0x0000)
struct BP_GameJoyPluginLibrary_SetAlbumName final
{
public:
	class FString                                 albumName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetAlbumName;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetAutoProfileLevel
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_SetAutoProfileLevel final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetAutoProfileLevel;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetCaptureSource
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_SetCaptureSource final
{
public:
	int32                                         CaptureSource;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetCaptureSource;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetCaptureTexture
// 0x0008 (0x0008 - 0x0000)
struct BP_GameJoyPluginLibrary_SetCaptureTexture final
{
public:
	class UTextureRenderTarget2D*                 RenderTarget;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetCaptureTexture;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetCaptureTextureFlipY
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_SetCaptureTextureFlipY final
{
public:
	bool                                          Flip;                                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetCaptureTextureFlipY;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetCoverSize
// 0x0008 (0x0008 - 0x0000)
struct BP_GameJoyPluginLibrary_SetCoverSize final
{
public:
	int32                                         Width;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Height;                                            // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetCoverSize;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetEnableBackbufferCallback
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_SetEnableBackbufferCallback final
{
public:
	bool                                          bEnable;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetEnableBackbufferCallback;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetFrameRate
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_SetFrameRate final
{
public:
	int32                                         FrameRate;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetFrameRate;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetGameUseColorSpace
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_SetGameUseColorSpace final
{
public:
	int32                                         colorSpace;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetGameUseColorSpace;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetGameUseRenderAPI
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_SetGameUseRenderAPI final
{
public:
	int32                                         api;                                               // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetGameUseRenderAPI;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetMinAvailableSpaceMB
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_SetMinAvailableSpaceMB final
{
public:
	int32                                         minAvailableSpaceMB;                               // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetMinAvailableSpaceMB;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetVideoBitrate
// 0x0008 (0x0008 - 0x0000)
struct BP_GameJoyPluginLibrary_SetVideoBitrate final
{
public:
	int32                                         Type;                                              // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         bitrate;                                           // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetVideoBitrate;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetVideoQuality
// 0x0004 (0x0004 - 0x0000)
struct BP_GameJoyPluginLibrary_SetVideoQuality final
{
public:
	int32                                         Quality;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetVideoQuality;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetVideoResolution
// 0x0008 (0x0008 - 0x0000)
struct BP_GameJoyPluginLibrary_SetVideoResolution final
{
public:
	int32                                         Type;                                              // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Resolution;                                        // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetVideoResolution;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetWatermark
// 0x0018 (0x0018 - 0x0000)
struct BP_GameJoyPluginLibrary_SetWatermark final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         X;                                                 // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Y;                                                 // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetWatermark;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.SetWwiseListenerStatus
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_SetWwiseListenerStatus final
{
public:
	bool                                          isMultiple;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_SetWwiseListenerStatus;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.ShowRecorderDialog
// 0x0008 (0x0008 - 0x0000)
struct BP_GameJoyPluginLibrary_ShowRecorderDialog final
{
public:
	float                                         X;                                                 // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Y;                                                 // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_ShowRecorderDialog;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.StartRecorder
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_StartRecorder final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_StartRecorder;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.UpdateRedDot
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_UpdateRedDot final
{
public:
	bool                                          showRedDot;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_UpdateRedDot;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.UseBackbuffer
// 0x0001 (0x0001 - 0x0000)
struct BP_GameJoyPluginLibrary_UseBackbuffer final
{
public:
	bool                                          use;                                               // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_UseBackbuffer;

// Function GameJoyPlugin.BP_GameJoyPluginLibrary.CopyFile
// 0x0028 (0x0028 - 0x0000)
struct BP_GameJoyPluginLibrary_CopyFile final
{
public:
	class FString                                 From;                                              // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 dst;                                               // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_BP_GameJoyPluginLibrary_CopyFile;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
