#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GamePad

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class GamePad.NRCHandleHelper
// 0x0020 (0x0048 - 0x0028)
class UNRCHandleHelper final : public UObject
{
public:
	uint8                                         Pad_28[0x20];                                      // 0x0028(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static bool IsEnabled();
	static bool IsGamepadConnected();
	static bool IsReady();
	static void SendData(const class FString& Data);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NRCHandleHelper")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NRCHandleHelper")
	}
	static class UNRCHandleHelper* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNRCHandleHelper>();
	}
};
DUMPER7_ASSERTS_UNRCHandleHelper;

SDK_NAMESPACE_END
