#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MagtModule

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "MagtModule_structs.hpp"
#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class MagtModule.MagtActor
// 0x0050 (0x0298 - 0x0248)
class AMagtActor final : public AActor
{
public:
	int32                                         CPUPerf;                                           // 0x0248(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CPULoad;                                           // 0x024C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GPUPerf;                                           // 0x0250(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         GPULoad;                                           // 0x0254(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Status;                                            // 0x0258(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Temperature;                                       // 0x025C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Power;                                             // 0x0260(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FPS;                                               // 0x0264(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TargetFPS;                                         // 0x0268(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_26C[0x2C];                                     // 0x026C(0x002C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MagtActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MagtActor")
	}
	static class AMagtActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMagtActor>();
	}
};
DUMPER7_ASSERTS_AMagtActor;

// Class MagtModule.MagtBufferTXManager
// 0x0030 (0x0058 - 0x0028)
class UMagtBufferTXManager final : public UObject
{
public:
	int32                                         HistorySize;                                       // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 BufferTXHistory;                                   // 0x0030(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_40[0x18];                                      // 0x0040(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ClearHistory();

	float GetAverageBufferTX() const;
	float GetBufferTXVariance() const;
	int32 GetHistoryCount() const;
	int32 GetLatestBufferTX() const;
	int64 GetLatestIdentifier() const;
	int32 GetLatestThreadID() const;
	int32 GetMaxBufferTX() const;
	int32 GetMinBufferTX() const;
	bool IsBufferTXIncreasing() const;
	bool IsBufferTXStable() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MagtBufferTXManager")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MagtBufferTXManager")
	}
	static class UMagtBufferTXManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMagtBufferTXManager>();
	}
};
DUMPER7_ASSERTS_UMagtBufferTXManager;

// Class MagtModule.MagtDebugHUD
// 0x0028 (0x0050 - 0x0028)
class UMagtDebugHUD final : public UObject
{
public:
	uint8                                         Pad_28[0x28];                                      // 0x0028(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetDisplayPosition(const struct FVector2D& position);
	void SetEnabled(bool bEnable);
	void SetFontScale(float Scale);
	void Toggle();

	bool IsEnabled() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MagtDebugHUD")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MagtDebugHUD")
	}
	static class UMagtDebugHUD* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMagtDebugHUD>();
	}
};
DUMPER7_ASSERTS_UMagtDebugHUD;

// Class MagtModule.MagtMipsCounter
// 0x00E0 (0x0108 - 0x0028)
class UMagtMipsCounter final : public UObject
{
public:
	uint8                                         Pad_28[0x80];                                      // 0x0028(0x0080)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FMagtCpuMipsData>               CpuMipsData;                                       // 0x00A8(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_B8[0x50];                                      // 0x00B8(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void Cleanup();
	int32 Initialize(bool bExcludeKernelSpace);
	bool StartCounting();
	bool StopAndUpdate();

	TArray<struct FMagtCpuMipsData> GetAllCpuMipsData() const;
	float GetAverageCpi() const;
	float GetAverageMcps() const;
	float GetAverageMips() const;
	float GetCpuCpi(int32 CpuId) const;
	float GetCpuMcps(int32 CpuId) const;
	float GetCpuMips(int32 CpuId) const;
	int64 GetTotalCycles() const;
	int64 GetTotalInstructions() const;
	float GetTotalMcps() const;
	float GetTotalMips() const;
	int32 GetValidCpuCount() const;
	bool IsInitialized() const;
	bool IsRunning() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MagtMipsCounter")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MagtMipsCounter")
	}
	static class UMagtMipsCounter* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMagtMipsCounter>();
	}
};
DUMPER7_ASSERTS_UMagtMipsCounter;

// Class MagtModule.MagtPerformanceBooster
// 0x0030 (0x0058 - 0x0028)
class UMagtPerformanceBooster final : public UObject
{
public:
	TMulticastInlineDelegate<void(bool bIsCPU, const struct FMagtBoostState& NewState)> OnBoostStateChanged; // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_38[0x20];                                      // 0x0038(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool BoostCPU(int32 Level, int32 durationMs, bool bBoostDRAM);
	bool BoostGPU(int32 Level, int32 durationMs, bool bBoostDRAM);
	bool BoostThreadsByID(const TArray<int32>& ThreadIDs, bool bEnable, int32 durationMs);
	bool BoostThreadsByName(const TArray<class FString>& ThreadNames, bool bEnable, int32 durationMs);
	bool DynamicBoostGPU(bool bEnable, int32 RenderThreadID, bool bBoostDRAM);
	struct FMagtBoostState QueryCPUBoostState();
	struct FMagtBoostState QueryGPUBoostState();
	bool SetThreadTargetFPS(int32 ThreadID, int32 TargetFPS);
	bool StopCPUBoost();
	bool StopGPUBoost();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MagtPerformanceBooster")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MagtPerformanceBooster")
	}
	static class UMagtPerformanceBooster* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMagtPerformanceBooster>();
	}
};
DUMPER7_ASSERTS_UMagtPerformanceBooster;

// Class MagtModule.MagtService
// 0x0050 (0x0078 - 0x0028)
class UMagtService final : public UObject
{
public:
	TMulticastInlineDelegate<void(bool bSuccess, int32 ResultCode)> OnInitialized;                   // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnServiceStarted;                                  // 0x0038(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnServiceStopped;                                  // 0x0048(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_58[0x20];                                      // 0x0058(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool GetAllPerformanceIndices(int32* OutCPUPerfIndex, int32* OutCPULoadIndex, int32* OutGPUPerfIndex, int32* OutGPULoadIndex);
	bool GetAllPowerIndices(int32* OutPCBTemp, int32* OutBatNowCurrent, int32* OutBatAvgCurrent, int32* OutThermalStatus);
	int32 GetBatteryAvgCurrent();
	int32 GetBatteryNowCurrent();
	int32 GetCPULoadIndex();
	int32 GetCPUPerfIndex();
	int32 GetGPULoadIndex();
	int32 GetGPUPerfIndex();
	int32 GetOption(int32 OptionID);
	int32 GetPCBTemperature();
	bool GetPerformanceReport(struct FMagtPerfReport* OutReport);
	int32 GetTargetFPS();
	int32 GetThermalStatus();
	bool InitGameConfig(int32 ConfigID, int32 Value);
	bool Initialize(const class FString& LicenseKey, int32 APIVersion, int32 GameCode, int32 TargetFPS, int32 RenderThreadID);
	bool InitializeWithSignature(const class FString& LicenseKey, const class FString& Signature, int32 APIVersion, int32 GameCode, int32 TargetFPS, int32 RenderThreadID);
	void Release();
	void SetDebugMode(bool bEnabled);
	void SetForeground(bool bIsForeground);
	bool SetOption(int32 OptionID, int32 Value);
	bool StartService(int32 ServiceFlags);
	bool StopService();
	void SyncRenderingFrameId(int32 FrameID);
	bool UpdateGameConfig(int32 ConfigID, int32 Value);

	int32 GetGameCode() const;
	int32 GetInitializationResult() const;
	bool IsInitialized() const;
	bool IsServiceRunning() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MagtService")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MagtService")
	}
	static class UMagtService* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMagtService>();
	}
};
DUMPER7_ASSERTS_UMagtService;

// Class MagtModule.MagtThreadManager
// 0x0050 (0x0078 - 0x0028)
class UMagtThreadManager final : public UObject
{
public:
	uint8                                         Pad_28[0x50];                                      // 0x0028(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static int32 GetCurrentThreadID();
	static int32 GetGameThreadID();
	static int32 GetRenderThreadID();
	static class FString ThreadGroupToString(EMagtThreadGroup Group);
	static class FString ThreadPriorityToString(EMagtThreadPriority Priority);

	bool BindThreadToCPU(int32 ThreadID, int32 CPUCore);
	bool RegisterCriticalThread(int32 ThreadID);
	bool RegisterCriticalThreads(const TArray<int32>& ThreadIDs);
	bool SetMainGameThreadInfo(int32 GameThreadID, int32 RenderThreadID);
	bool SetThreadGroup(int32 ThreadID, EMagtThreadGroup Group);
	bool SetThreadPriority(int32 ThreadID, EMagtThreadPriority Priority);
	bool UnbindThreadFromCPU(int32 ThreadID);
	bool UnregisterCriticalThread(int32 ThreadID);
	bool UnregisterCriticalThreads(const TArray<int32>& ThreadIDs);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MagtThreadManager")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MagtThreadManager")
	}
	static class UMagtThreadManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMagtThreadManager>();
	}
};
DUMPER7_ASSERTS_UMagtThreadManager;

// Class MagtModule.MagtWorkloadAdvisor
// 0x0020 (0x0048 - 0x0028)
class UMagtWorkloadAdvisor final : public UObject
{
public:
	TMulticastInlineDelegate<void(EMagtWorkloadAdvice NewAdvice, const struct FMagtPerfReport& PerfReport)> OnWorkloadAdviceChanged; // 0x0028(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_38[0x10];                                      // 0x0038(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static bool IsCPUBound(EMagtWorkloadAdvice Advice);
	static bool IsGPUBound(EMagtWorkloadAdvice Advice);
	static bool ShouldDowngradeQuality(EMagtWorkloadAdvice Advice);
	static bool ShouldUpgradeQuality(EMagtWorkloadAdvice Advice);
	static class FString WorkloadAdviceToString(EMagtWorkloadAdvice Advice);

	EMagtWorkloadAdvice GetWorkloadAdvice();
	int32 QueryScenario();
	bool SetWorkloadHint(int32 Hint);
	void StartPollingAdvice(float PollingIntervalSeconds);
	void StopPollingAdvice();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MagtWorkloadAdvisor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MagtWorkloadAdvisor")
	}
	static class UMagtWorkloadAdvisor* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMagtWorkloadAdvisor>();
	}
};
DUMPER7_ASSERTS_UMagtWorkloadAdvisor;

SDK_NAMESPACE_END
