#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MFInputReplayTool

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum MFInputReplayTool.ECharacterRecordDataType
// NumValues: 0x001F
enum class ECharacterRecordDataType : uint8
{
	InputAxis                                = 0,
	InputTouch                               = 1,
	InputKey                                 = 2,
	Clicked                                  = 3,
	Pressed                                  = 4,
	Released                                 = 5,
	Hovered                                  = 6,
	Unhovered                                = 7,
	State                                    = 8,
	Move                                     = 9,
	Pitch                                    = 10,
	Yaw                                      = 11,
	Roll                                     = 12,
	CPitch                                   = 13,
	CYaw                                     = 14,
	CRoll                                    = 15,
	TouchStart                               = 16,
	TouchEnd                                 = 17,
	Scroll                                   = 18,
	Endurance                                = 19,
	CharacterInfo                            = 20,
	ExecUE4Command                           = 21,
	GrabUIFeature                            = 22,
	DoLuaString                              = 23,
	RemoteSendBack                           = 24,
	KeyUp                                    = 25,
	KeyDown                                  = 26,
	KeyChar                                  = 27,
	MouseButtonDown                          = 28,
	MouseButtonUp                            = 29,
	ECharacterRecordDataType_MAX             = 30,
};

// Enum MFInputReplayTool.ERepayStep
// NumValues: 0x000B
enum class ERepayStep : uint8
{
	Idle                                     = 0,
	RecordDownloading                        = 1,
	RecordDownloadSuccess                    = 2,
	RecordDownloadFail                       = 3,
	RequestStartReplay                       = 4,
	CountDown                                = 5,
	Running                                  = 6,
	Success                                  = 7,
	Fail                                     = 8,
	Cancel                                   = 9,
	ERepayStep_MAX                           = 10,
};

SDK_NAMESPACE_END
