#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MFTPerformanceHeatmap

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// Enum MFTPerformanceHeatmap.ETestEnvMode
// NumValues: 0x0003
enum class ETestEnvMode : uint8
{
	ProdEnv                                  = 0,
	DevEnv                                   = 1,
	ETestEnvMode_MAX                         = 2,
};

// Enum MFTPerformanceHeatmap.ERunPerfBatchPointType
// NumValues: 0x0004
enum class ERunPerfBatchPointType : uint8
{
	Horizontal                               = 0,
	LookingDown                              = 1,
	PSOHorizontal                            = 2,
	ERunPerfBatchPointType_MAX               = 3,
};

// Enum MFTPerformanceHeatmap.EDebugMode
// NumValues: 0x0004
enum class EDebugMode : uint8
{
	Default                                  = 0,
	StepDebug                                = 1,
	Num                                      = 2,
	EDebugMode_MAX                           = 3,
};

// Enum MFTPerformanceHeatmap.ERunPerfLazyConfig
// NumValues: 0x0007
enum class ERunPerfLazyConfig : uint8
{
	Default                                  = 0,
	CSMCache                                 = 1,
	DefaultLookingDown                       = 2,
	CSMCacheLookingDown                      = 3,
	PSO                                      = 4,
	Num                                      = 5,
	ERunPerfLazyConfig_MAX                   = 6,
};

// ScriptStruct MFTPerformanceHeatmap.TestPose
// 0x0024 (0x0024 - 0x0000)
struct FTestPose final
{
public:
	struct FVector                                Location;                                          // 0x0000(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               Rotator;                                           // 0x000C(0x000C)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bRuntimeZAxisLineTrace;                            // 0x0018(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ZAxisLineTraceStartPos;                            // 0x001C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ZAxisLineTraceFlyHeight;                           // 0x0020(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FTestPose;

// ScriptStruct MFTPerformanceHeatmap.ManualPointCollection
// 0x0030 (0x0030 - 0x0000)
struct FManualPointCollection final
{
public:
	class FString                                 Name;                                              // 0x0000(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FVector>                        BatchPoints;                                       // 0x0010(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<struct FTestPose>                      Poses;                                             // 0x0020(0x0010)(Edit, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FManualPointCollection;

// ScriptStruct MFTPerformanceHeatmap.RestCollectStep
// 0x0008 (0x0008 - 0x0000)
struct FRestCollectStep final
{
public:
	int32                                         RestTime;                                          // 0x0000(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CollectTicks;                                      // 0x0004(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FRestCollectStep;

// ScriptStruct MFTPerformanceHeatmap.BatchPointArea
// 0x0034 (0x0034 - 0x0000)
struct FBatchPointArea final
{
public:
	struct FIntPoint                              MinTileIndex;                                      // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FIntPoint                              MaxTileIndex;                                      // 0x0008(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         IntervalDistance;                                  // 0x0010(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bGenBatchPoints;                                   // 0x0014(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCustomBoundBox;                                   // 0x0015(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_16[0x2];                                       // 0x0016(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              GenerateOffset;                                    // 0x0018(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FBox2D                                 BoundBox;                                          // 0x0020(0x0014)(Edit, ZeroConstructor, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FBatchPointArea;

SDK_NAMESPACE_END
