#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NRCActorTagSubSystem

#include "Basic.hpp"

#include "DeveloperSettings_classes.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class NRCActorTagSubSystem.ActorTagSubSystemSettings
// 0x0010 (0x0048 - 0x0038)
class UActorTagSubSystemSettings final : public UDeveloperSettings
{
public:
	TArray<class FName>                           TagSubSystemTags;                                  // 0x0038(0x0010)(Edit, ZeroConstructor, Config, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActorTagSubSystemSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActorTagSubSystemSettings")
	}
	static class UActorTagSubSystemSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActorTagSubSystemSettings>();
	}
};
DUMPER7_ASSERTS_UActorTagSubSystemSettings;

// Class NRCActorTagSubSystem.ActorTagSubSystem
// 0x0058 (0x0088 - 0x0030)
class UActorTagSubSystem final : public UWorldSubsystem
{
public:
	uint8                                         Pad_30[0x58];                                      // 0x0030(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static void GetActorsByTag(const class UObject* WorldContextObject, const class FName& Tag, TArray<class AActor*>* OutActors);
	static void GetActorsByTagEditorOnly(const class UObject* WorldContextObject, const class FName& Tag, TArray<class AActor*>* OutActors);

	void AddActor(class AActor* Actor);
	void OnActorEndPlay(class AActor* Actor, EEndPlayReason EndPlayReason);
	void RemoveActor(class AActor* Actor);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("ActorTagSubSystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ActorTagSubSystem")
	}
	static class UActorTagSubSystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActorTagSubSystem>();
	}
};
DUMPER7_ASSERTS_UActorTagSubSystem;

SDK_NAMESPACE_END
