#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NRCActorTagSubSystem

#include "Basic.hpp"

#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function NRCActorTagSubSystem.ActorTagSubSystem.GetActorsByTag
// 0x0020 (0x0020 - 0x0000)
struct ActorTagSubSystem_GetActorsByTag final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   Tag;                                               // 0x0008(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class AActor*>                         OutActors;                                         // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ActorTagSubSystem_GetActorsByTag;

// Function NRCActorTagSubSystem.ActorTagSubSystem.GetActorsByTagEditorOnly
// 0x0020 (0x0020 - 0x0000)
struct ActorTagSubSystem_GetActorsByTagEditorOnly final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   Tag;                                               // 0x0008(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class AActor*>                         OutActors;                                         // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ActorTagSubSystem_GetActorsByTagEditorOnly;

// Function NRCActorTagSubSystem.ActorTagSubSystem.AddActor
// 0x0008 (0x0008 - 0x0000)
struct ActorTagSubSystem_AddActor final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ActorTagSubSystem_AddActor;

// Function NRCActorTagSubSystem.ActorTagSubSystem.OnActorEndPlay
// 0x0010 (0x0010 - 0x0000)
struct ActorTagSubSystem_OnActorEndPlay final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EEndPlayReason                                EndPlayReason;                                     // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ActorTagSubSystem_OnActorEndPlay;

// Function NRCActorTagSubSystem.ActorTagSubSystem.RemoveActor
// 0x0008 (0x0008 - 0x0000)
struct ActorTagSubSystem_RemoveActor final
{
public:
	class AActor*                                 Actor;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ActorTagSubSystem_RemoveActor;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
