#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NRCHomePOIRuntime

#include "Basic.hpp"

#include "NRCHomePOIRuntime_classes.hpp"


SDK_NAMESPACE_START

// Function NRCHomePOIRuntime.NRCHomePOIRuntimeComponent.OnPoiRegister
// (Event, Public, BlueprintEvent)

void UNRCHomePOIRuntimeComponent::OnPoiRegister()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NRCHomePOIRuntimeComponent", "OnPoiRegister");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NRCHomePOIRuntime.NRCHomePOIRuntimeComponent.OnPoiUnregister
// (Event, Public, BlueprintEvent)

void UNRCHomePOIRuntimeComponent::OnPoiUnregister()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NRCHomePOIRuntimeComponent", "OnPoiUnregister");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
