#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NRCPatchRuntime

#include "Basic.hpp"

#include "NRCPatchRuntime_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function NRCPatchRuntime.HotUpdateUtils.CreatePakReader
// 0x0020 (0x0020 - 0x0000)
struct HotUpdateUtils_CreatePakReader final
{
public:
	class FString                                 InFilename;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bLoadIndex;                                        // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPakReader*                             ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_HotUpdateUtils_CreatePakReader;

// Function NRCPatchRuntime.HotUpdateUtils.CreatePakWriter
// 0x0040 (0x0040 - 0x0000)
struct HotUpdateUtils_CreatePakWriter final
{
public:
	class FString                                 InFilename;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 InMountPoint;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 CryptoPath;                                        // 0x0020(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEncryptIndex;                                     // 0x0030(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UPakWriter*                             ReturnValue;                                       // 0x0038(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_HotUpdateUtils_CreatePakWriter;

// Function NRCPatchRuntime.HotUpdateUtils.GetContentPipelineCachePath
// 0x0010 (0x0010 - 0x0000)
struct HotUpdateUtils_GetContentPipelineCachePath final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_HotUpdateUtils_GetContentPipelineCachePath;

// Function NRCPatchRuntime.HotUpdateUtils.GetPipelineCachePatchPath
// 0x0010 (0x0010 - 0x0000)
struct HotUpdateUtils_GetPipelineCachePatchPath final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_HotUpdateUtils_GetPipelineCachePatchPath;

// Function NRCPatchRuntime.HotUpdateUtils.GetProjectName
// 0x0010 (0x0010 - 0x0000)
struct HotUpdateUtils_GetProjectName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_HotUpdateUtils_GetProjectName;

// Function NRCPatchRuntime.HotUpdateUtils.GetStrippedConfigFileName
// 0x0020 (0x0020 - 0x0000)
struct HotUpdateUtils_GetStrippedConfigFileName final
{
public:
	class FString                                 IniName;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_HotUpdateUtils_GetStrippedConfigFileName;

// Function NRCPatchRuntime.HotUpdateUtils.GetUpdateConfigFileURL
// 0x0038 (0x0038 - 0x0000)
struct HotUpdateUtils_GetUpdateConfigFileURL final
{
public:
	bool                                          bRelease;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Filename;                                          // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ClientBranch;                                      // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0028(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_HotUpdateUtils_GetUpdateConfigFileURL;

// Function NRCPatchRuntime.HotUpdateUtils.IsPakMounted
// 0x0018 (0x0018 - 0x0000)
struct HotUpdateUtils_IsPakMounted final
{
public:
	class FString                                 PakFilename;                                       // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_HotUpdateUtils_IsPakMounted;

// Function NRCPatchRuntime.HotUpdateUtils.MountPak
// 0x0018 (0x0018 - 0x0000)
struct HotUpdateUtils_MountPak final
{
public:
	class FString                                 PakFilename;                                       // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PakOrder;                                          // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0014(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_HotUpdateUtils_MountPak;

// Function NRCPatchRuntime.HotUpdateUtils.OpenShaderPatchLibrary
// 0x0028 (0x0028 - 0x0000)
struct HotUpdateUtils_OpenShaderPatchLibrary final
{
public:
	class FString                                 ShaderPatchLibraryName;                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 LibraryDir;                                        // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShaderPatchLibUnique;                             // 0x0020(0x0001)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0021(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_HotUpdateUtils_OpenShaderPatchLibrary;

// Function NRCPatchRuntime.HotUpdateUtils.ReadEncryptedJsonData
// 0x0028 (0x0028 - 0x0000)
struct HotUpdateUtils_ReadEncryptedJsonData final
{
public:
	class FString                                 ConfigPath;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 OutData;                                           // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_HotUpdateUtils_ReadEncryptedJsonData;

// Function NRCPatchRuntime.HotUpdateUtils.ReloadIniFile
// 0x0028 (0x0028 - 0x0000)
struct HotUpdateUtils_ReloadIniFile final
{
public:
	class FString                                 StrippedConfigFileName;                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 FilePath;                                          // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_HotUpdateUtils_ReloadIniFile;

// Function NRCPatchRuntime.HotUpdateUtils.ReloadRedirectSettingsFromIni
// 0x0010 (0x0010 - 0x0000)
struct HotUpdateUtils_ReloadRedirectSettingsFromIni final
{
public:
	class FString                                 IniPath;                                           // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_HotUpdateUtils_ReloadRedirectSettingsFromIni;

// Function NRCPatchRuntime.HotUpdateUtils.TryGetResFileHash
// 0x0028 (0x0028 - 0x0000)
struct HotUpdateUtils_TryGetResFileHash final
{
public:
	class FString                                 FilePath;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Hash;                                              // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_HotUpdateUtils_TryGetResFileHash;

// Function NRCPatchRuntime.HotUpdateUtils.UnmountPak
// 0x0018 (0x0018 - 0x0000)
struct HotUpdateUtils_UnmountPak final
{
public:
	class FString                                 PakFilename;                                       // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_HotUpdateUtils_UnmountPak;

// Function NRCPatchRuntime.HotUpdateUtils.WriteSpecifiedDirAllPakIndexDataIntoJson
// 0x0028 (0x0028 - 0x0000)
struct HotUpdateUtils_WriteSpecifiedDirAllPakIndexDataIntoJson final
{
public:
	class FString                                 SrcDir;                                            // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SaveFullPath;                                      // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bOnlyHash;                                         // 0x0020(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bOnlyPatch;                                        // 0x0021(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0022(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_23[0x5];                                       // 0x0023(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_HotUpdateUtils_WriteSpecifiedDirAllPakIndexDataIntoJson;

// Function NRCPatchRuntime.NRCAsyncFileVerifyTask.CreateAsyncFileVerifyTask
// 0x0008 (0x0008 - 0x0000)
struct NRCAsyncFileVerifyTask_CreateAsyncFileVerifyTask final
{
public:
	class UNRCAsyncFileVerifyTask*                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_NRCAsyncFileVerifyTask_CreateAsyncFileVerifyTask;

// Function NRCPatchRuntime.NRCAsyncFileVerifyTask.AsyncVerifyFiles
// 0x0020 (0x0020 - 0x0000)
struct NRCAsyncFileVerifyTask_AsyncVerifyFiles final
{
public:
	TArray<class FString>                         FilePathList;                                      // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	float                                         UpdateFrequency;                                   // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_NRCAsyncFileVerifyTask_AsyncVerifyFiles;

// Function NRCPatchRuntime.NRCAsyncFileVerifyTask.AsyncVerifyLocalFiles
// 0x0020 (0x0020 - 0x0000)
struct NRCAsyncFileVerifyTask_AsyncVerifyLocalFiles final
{
public:
	TArray<class FString>                         ToSearchDirList;                                   // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	float                                         UpdateFrequency;                                   // 0x0010(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	int64                                         ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_NRCAsyncFileVerifyTask_AsyncVerifyLocalFiles;

// Function NRCPatchRuntime.PakReader.GetHash
// 0x0010 (0x0010 - 0x0000)
struct PakReader_GetHash final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PakReader_GetHash;

// Function NRCPatchRuntime.PakReader.GetMountPoint
// 0x0010 (0x0010 - 0x0000)
struct PakReader_GetMountPoint final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PakReader_GetMountPoint;

// Function NRCPatchRuntime.PakReader.GetPakIndex
// 0x0010 (0x0010 - 0x0000)
struct PakReader_GetPakIndex final
{
public:
	TArray<struct FPakEntryInfo>                  ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PakReader_GetPakIndex;

// Function NRCPatchRuntime.PakReader.GetPakIndexOffset
// 0x0008 (0x0008 - 0x0000)
struct PakReader_GetPakIndexOffset final
{
public:
	int64                                         ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PakReader_GetPakIndexOffset;

// Function NRCPatchRuntime.PakReader.GetTotalSize
// 0x0008 (0x0008 - 0x0000)
struct PakReader_GetTotalSize final
{
public:
	int64                                         ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PakReader_GetTotalSize;

// Function NRCPatchRuntime.PakWriter.AddDeleteFile
// 0x0018 (0x0018 - 0x0000)
struct PakWriter_AddDeleteFile final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_PakWriter_AddDeleteFile;

// Function NRCPatchRuntime.PakWriter.AddFileFromFile
// 0x0050 (0x0050 - 0x0000)
struct PakWriter_AddFileFromFile final
{
public:
	class FString                                 Filename;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 SrcFilePath;                                       // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         Offset;                                            // 0x0020(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         EndOffset;                                         // 0x0028(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int64                                         EntrySize;                                         // 0x0030(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           CompressionMethods;                                // 0x0038(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0048(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_PakWriter_AddFileFromFile;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
