#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OculusMR

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "OculusMR_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class OculusMR.OculusMR_CastingCameraActor
// 0x00F0 (0x0350 - 0x0260)
class alignas(0x10) AOculusMR_CastingCameraActor final : public ASceneCapture2D
{
public:
	class UVRNotificationsComponent*              VRNotificationComponent;                           // 0x0260(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             CameraColorTexture;                                // 0x0268(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             CameraDepthTexture;                                // 0x0270(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UOculusMR_PlaneMeshComponent*           PlaneMeshComponent;                                // 0x0278(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterial*                              ChromaKeyMaterial;                                 // 0x0280(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterial*                              OpaqueColoredMaterial;                             // 0x0288(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstanceDynamic*               ChromaKeyMaterialInstance;                         // 0x0290(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstanceDynamic*               CameraFrameMaterialInstance;                       // 0x0298(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstanceDynamic*               BackdropMaterialInstance;                          // 0x02A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             DefaultTexture_White;                              // 0x02A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2B0[0x58];                                     // 0x02B0(0x0058)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UTextureRenderTarget2D*>         BackgroundRenderTargets;                           // 0x0308(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	class ASceneCapture2D*                        ForegroundCaptureActor;                            // 0x0318(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	TArray<class UTextureRenderTarget2D*>         ForegroundRenderTargets;                           // 0x0320(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	TArray<double>                                PoseTimes;                                         // 0x0330(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	class UOculusMR_Settings*                     MRSettings;                                        // 0x0340(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	class UOculusMR_State*                        MRState;                                           // 0x0348(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OculusMR_CastingCameraActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OculusMR_CastingCameraActor")
	}
	static class AOculusMR_CastingCameraActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOculusMR_CastingCameraActor>();
	}
};
DUMPER7_ASSERTS_AOculusMR_CastingCameraActor;

// Class OculusMR.OculusMR_PlaneMeshComponent
// 0x0020 (0x0590 - 0x0570)
class UOculusMR_PlaneMeshComponent final : public UMeshComponent
{
public:
	uint8                                         Pad_570[0x20];                                     // 0x0570(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void AddCustomMeshTriangles(const TArray<struct FOculusMR_PlaneMeshTriangle>& Triangles);
	void ClearCustomMeshTriangles();
	bool SetCustomMeshTriangles(const TArray<struct FOculusMR_PlaneMeshTriangle>& Triangles);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OculusMR_PlaneMeshComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OculusMR_PlaneMeshComponent")
	}
	static class UOculusMR_PlaneMeshComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOculusMR_PlaneMeshComponent>();
	}
};
DUMPER7_ASSERTS_UOculusMR_PlaneMeshComponent;

// Class OculusMR.OculusMR_Settings
// 0x0070 (0x0098 - 0x0028)
class UOculusMR_Settings final : public UObject
{
public:
	EOculusMR_ClippingReference                   ClippingReference;                                 // 0x0028(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUseTrackedCameraResolution;                       // 0x0029(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2A[0x2];                                       // 0x002A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         WidthPerView;                                      // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HeightPerView;                                     // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CastingLatency;                                    // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 BackdropColor;                                     // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         HandPoseStateLatency;                              // 0x003C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 ChromaKeyColor;                                    // 0x0040(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ChromaKeySimilarity;                               // 0x0044(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ChromaKeySmoothRange;                              // 0x0048(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ChromaKeySpillRange;                               // 0x004C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EOculusMR_PostProcessEffects                  ExternalCompositionPostProcessEffects;             // 0x0050(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsCasting;                                        // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	EOculusMR_CompositionMethod                   CompositionMethod;                                 // 0x0052(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	EOculusMR_CameraDeviceEnum                    CapturingCamera;                                   // 0x0053(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_54[0x44];                                      // 0x0054(0x0044)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void BindToTrackedCameraIndexIfAvailable(int32 InTrackedCameraIndex);
	int32 GetBindToTrackedCameraIndex();
	EOculusMR_CameraDeviceEnum GetCapturingCamera();
	EOculusMR_CompositionMethod GetCompositionMethod();
	bool GetIsCasting();
	void LoadFromIni();
	void SetCapturingCamera(EOculusMR_CameraDeviceEnum Val);
	void SetCompositionMethod(EOculusMR_CompositionMethod Val);
	void SetIsCasting(bool Val);

	void SaveToIni() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OculusMR_Settings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OculusMR_Settings")
	}
	static class UOculusMR_Settings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOculusMR_Settings>();
	}
};
DUMPER7_ASSERTS_UOculusMR_Settings;

// Class OculusMR.OculusMR_State
// 0x0090 (0x00B8 - 0x0028)
class UOculusMR_State final : public UObject
{
public:
	struct FTrackedCamera                         TrackedCamera;                                     // 0x0028(0x0078)(NativeAccessSpecifierPublic)
	class USceneComponent*                        TrackingReferenceComponent;                        // 0x00A0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	double                                        ScalingFactor;                                     // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B0[0x4];                                       // 0x00B0(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          ChangeCameraStateRequested;                        // 0x00B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          BindToTrackedCameraIndexRequested;                 // 0x00B5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B6[0x2];                                       // 0x00B6(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OculusMR_State")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OculusMR_State")
	}
	static class UOculusMR_State* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOculusMR_State>();
	}
};
DUMPER7_ASSERTS_UOculusMR_State;

// Class OculusMR.OculusMRFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UOculusMRFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static float GetMrcScalingFactor();
	static class UOculusMR_Settings* GetOculusMRSettings();
	static class USceneComponent* GetTrackingReferenceComponent();
	static bool IsMrcActive();
	static bool IsMrcEnabled();
	static bool SetMrcScalingFactor(float ScalingFactor);
	static bool SetTrackingReferenceComponent(class USceneComponent* Component);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("OculusMRFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OculusMRFunctionLibrary")
	}
	static class UOculusMRFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOculusMRFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UOculusMRFunctionLibrary;

SDK_NAMESPACE_END
