#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PandoraVideoPlayer

#include "Basic.hpp"

#include "PandoraVideoPlayer_classes.hpp"
#include "PandoraVideoPlayer_parameters.hpp"


SDK_NAMESPACE_START

// Function PandoraVideoPlayer.BP_PixVideoLibrary.CreatePlayerWidget
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Name_0                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UUserWidget*                      ReturnValue                                            (ExportObject, Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UUserWidget* UBP_PixVideoLibrary::CreatePlayerWidget(const class FString& Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_PixVideoLibrary", "CreatePlayerWidget");

	Params::BP_PixVideoLibrary_CreatePlayerWidget Parms{};

	Parms.Name_0 = std::move(Name_0);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.ClearCacheResource
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    cachePath                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::ClearCacheResource(const class FString& cachePath)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "ClearCacheResource");

	Params::PVideoImage_ClearCacheResource Parms{};

	Parms.cachePath = std::move(cachePath);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.Close
// (Final, Native, Public, BlueprintCallable)

void UPVideoImage::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "Close");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.EnableCacheResource
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bEnable                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    cachePath                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::EnableCacheResource(bool bEnable, const class FString& cachePath)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "EnableCacheResource");

	Params::PVideoImage_EnableCacheResource Parms{};

	Parms.bEnable = bEnable;
	Parms.cachePath = std::move(cachePath);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.GetAlphaParameter
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FLinearColor               ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const struct FLinearColor UPVideoImage::GetAlphaParameter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetAlphaParameter");

	Params::PVideoImage_GetAlphaParameter Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.GetCurrentPosition
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoImage::GetCurrentPosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetCurrentPosition");

	Params::PVideoImage_GetCurrentPosition Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.GetDuration
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoImage::GetDuration()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetDuration");

	Params::PVideoImage_GetDuration Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.GetMediaType
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoImage::GetMediaType()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetMediaType");

	Params::PVideoImage_GetMediaType Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.GetPlayStatus
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoImage::GetPlayStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetPlayStatus");

	Params::PVideoImage_GetPlayStatus Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.GetResolution
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// int32*                                  nWidth                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32*                                  nHeight                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::GetResolution(int32* nWidth, int32* nHeight)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetResolution");

	Params::PVideoImage_GetResolution Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (nWidth != nullptr)
		*nWidth = Parms.nWidth;

	if (nHeight != nullptr)
		*nHeight = Parms.nHeight;
}


// Function PandoraVideoPlayer.PVideoImage.GetRgbParameter
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FLinearColor               ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const struct FLinearColor UPVideoImage::GetRgbParameter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetRgbParameter");

	Params::PVideoImage_GetRgbParameter Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.GetVideoAlpha
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UPVideoImage::GetVideoAlpha()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetVideoAlpha");

	Params::PVideoImage_GetVideoAlpha Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.GetVideoTexture
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nIdx                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UTexture2D*                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UTexture2D* UPVideoImage::GetVideoTexture(int32 nIdx)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetVideoTexture");

	Params::PVideoImage_GetVideoTexture Parms{};

	Parms.nIdx = nIdx;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.GetVideoTime
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// float*                                  fCurTime                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float*                                  fTotalTime                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::GetVideoTime(float* fCurTime, float* fTotalTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetVideoTime");

	Params::PVideoImage_GetVideoTime Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (fCurTime != nullptr)
		*fCurTime = Parms.fCurTime;

	if (fTotalTime != nullptr)
		*fTotalTime = Parms.fTotalTime;
}


// Function PandoraVideoPlayer.PVideoImage.GetYUVFormat
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoImage::GetYUVFormat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "GetYUVFormat");

	Params::PVideoImage_GetYUVFormat Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.IsAlphaVideo
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPVideoImage::IsAlphaVideo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "IsAlphaVideo");

	Params::PVideoImage_IsAlphaVideo Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.IsPause
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPVideoImage::IsPause()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "IsPause");

	Params::PVideoImage_IsPause Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.IsPlaying
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPVideoImage::IsPlaying()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "IsPlaying");

	Params::PVideoImage_IsPlaying Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.IsTextureUpdated
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPVideoImage::IsTextureUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "IsTextureUpdated");

	Params::PVideoImage_IsTextureUpdated Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.Pause
// (Final, Native, Public, BlueprintCallable)

void UPVideoImage::Pause()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "Pause");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.Play
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    StrUrl                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bLoop                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoImage::Play(const class FString& StrUrl, bool bLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "Play");

	Params::PVideoImage_Play Parms{};

	Parms.StrUrl = std::move(StrUrl);
	Parms.bLoop = bLoop;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.PlayOnceAndLoopBetween
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    StrUrl                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   nStartMs                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   nEndMs                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoImage::PlayOnceAndLoopBetween(const class FString& StrUrl, int32 nStartMs, int32 nEndMs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "PlayOnceAndLoopBetween");

	Params::PVideoImage_PlayOnceAndLoopBetween Parms{};

	Parms.StrUrl = std::move(StrUrl);
	Parms.nStartMs = nStartMs;
	Parms.nEndMs = nEndMs;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.PlayWithFd
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nFd                                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bLoop                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoImage::PlayWithFd(int32 nFd, bool bLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "PlayWithFd");

	Params::PVideoImage_PlayWithFd Parms{};

	Parms.nFd = nFd;
	Parms.bLoop = bLoop;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.Resume
// (Final, Native, Public, BlueprintCallable)

void UPVideoImage::Resume()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "Resume");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.Seek
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nSecond                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::Seek(int32 nSecond)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "Seek");

	Params::PVideoImage_Seek Parms{};

	Parms.nSecond = nSecond;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SeekAndPause
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nMilliSec                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SeekAndPause(int32 nMilliSec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SeekAndPause");

	Params::PVideoImage_SeekAndPause Parms{};

	Parms.nMilliSec = nMilliSec;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SeekMs
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   millisec                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SeekMs(int32 millisec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SeekMs");

	Params::PVideoImage_SeekMs Parms{};

	Parms.millisec = millisec;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetAutoPlay
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    doAutoPlay                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SetAutoPlay(bool doAutoPlay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetAutoPlay");

	Params::PVideoImage_SetAutoPlay Parms{};

	Parms.doAutoPlay = doAutoPlay;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetDataUpdateCallback
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TScriptInterface<class IPVideoPlayerInterface>dataUpdateInterface                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, NativeAccessSpecifierPublic)

void UPVideoImage::SetDataUpdateCallback(TScriptInterface<class IPVideoPlayerInterface> dataUpdateInterface)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetDataUpdateCallback");

	Params::PVideoImage_SetDataUpdateCallback Parms{};

	Parms.dataUpdateInterface = dataUpdateInterface;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetDecryptionKey
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    decryptionKey                                          (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoImage::SetDecryptionKey(const class FString& decryptionKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetDecryptionKey");

	Params::PVideoImage_SetDecryptionKey Parms{};

	Parms.decryptionKey = std::move(decryptionKey);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoImage.SetHardwareDecodec
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bHareware                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SetHardwareDecodec(bool bHareware)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetHardwareDecodec");

	Params::PVideoImage_SetHardwareDecodec Parms{};

	Parms.bHareware = bHareware;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetNeedPlayAudio
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    needPlayAudio                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SetNeedPlayAudio(bool needPlayAudio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetNeedPlayAudio");

	Params::PVideoImage_SetNeedPlayAudio Parms{};

	Parms.needPlayAudio = needPlayAudio;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetNeedVideoTexture
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    needVideoTexture                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SetNeedVideoTexture(bool needVideoTexture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetNeedVideoTexture");

	Params::PVideoImage_SetNeedVideoTexture Parms{};

	Parms.needVideoTexture = needVideoTexture;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetNextVideo
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    StrUrl                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bLoop                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SetNextVideo(const class FString& StrUrl, bool bLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetNextVideo");

	Params::PVideoImage_SetNextVideo Parms{};

	Parms.StrUrl = std::move(StrUrl);
	Parms.bLoop = bLoop;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetOnlyPlayType
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   Type                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SetOnlyPlayType(int32 Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetOnlyPlayType");

	Params::PVideoImage_SetOnlyPlayType Parms{};

	Parms.Type = Type;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetRate
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   nRate                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SetRate(float nRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetRate");

	Params::PVideoImage_SetRate Parms{};

	Parms.nRate = nRate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetStopAsyn
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   stopAsyn                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SetStopAsyn(int32 stopAsyn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetStopAsyn");

	Params::PVideoImage_SetStopAsyn Parms{};

	Parms.stopAsyn = stopAsyn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetVideoAlpha
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   fAlpha                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SetVideoAlpha(float fAlpha)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetVideoAlpha");

	Params::PVideoImage_SetVideoAlpha Parms{};

	Parms.fAlpha = fAlpha;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.SetVolume
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nVolume                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::SetVolume(int32 nVolume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "SetVolume");

	Params::PVideoImage_SetVolume Parms{};

	Parms.nVolume = nVolume;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.Update
// (Final, Native, Public, BlueprintCallable)

void UPVideoImage::Update()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "Update");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoImage.UseFileDelegate
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bEnable                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoImage::UseFileDelegate(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoImage", "UseFileDelegate");

	Params::PVideoImage_UseFileDelegate Parms{};

	Parms.bEnable = bEnable;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayerInterface.OnAudioDataUpdateCallback
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<uint8>&                    audioData                                              (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// int32                                   Size                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   Samples                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   Channels                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   sample_rate                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   clock                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool IPVideoPlayerInterface::OnAudioDataUpdateCallback(const TArray<uint8>& audioData, int32 Size, int32 Samples, int32 Channels, int32 sample_rate, float clock)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("PVideoPlayerInterface", "OnAudioDataUpdateCallback");

	Params::PVideoPlayerInterface_OnAudioDataUpdateCallback Parms{};

	Parms.audioData = std::move(audioData);
	Parms.Size = Size;
	Parms.Samples = Samples;
	Parms.Channels = Channels;
	Parms.sample_rate = sample_rate;
	Parms.clock = clock;

	AsUObject()->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.ClearCacheResource
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// const class FString&                    cachePath                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::ClearCacheResource(const class FString& cachePath)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PVideoPlayer", "ClearCacheResource");

	Params::PVideoPlayer_ClearCacheResource Parms{};

	Parms.cachePath = std::move(cachePath);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.InitPVideo
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPVideoPlayer::InitPVideo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PVideoPlayer", "InitPVideo");

	Params::PVideoPlayer_InitPVideo Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetCachePacketSize
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// int32                                   nSizeMb                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetCachePacketSize(int32 nSizeMb)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PVideoPlayer", "SetCachePacketSize");

	Params::PVideoPlayer_SetCachePacketSize Parms{};

	Parms.nSizeMb = nSizeMb;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetHardwareDecodec
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// bool                                    bHareware                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetHardwareDecodec(bool bHareware)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PVideoPlayer", "SetHardwareDecodec");

	Params::PVideoPlayer_SetHardwareDecodec Parms{};

	Parms.bHareware = bHareware;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetStopAsyn
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// int32                                   stopAsyn                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetStopAsyn(int32 stopAsyn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("PVideoPlayer", "SetStopAsyn");

	Params::PVideoPlayer_SetStopAsyn Parms{};

	Parms.stopAsyn = stopAsyn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.BeginPlay
// (Event, Public, BlueprintEvent)

void UPVideoPlayer::BeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "BeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PandoraVideoPlayer.PVideoPlayer.BlueTick
// (Event, Public, BlueprintEvent)

void UPVideoPlayer::BlueTick()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "BlueTick");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PandoraVideoPlayer.PVideoPlayer.Close
// (Final, Native, Public, BlueprintCallable)

void UPVideoPlayer::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "Close");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.EnableCacheResource
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bEnable                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    cachePath                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::EnableCacheResource(bool bEnable, const class FString& cachePath)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "EnableCacheResource");

	Params::PVideoPlayer_EnableCacheResource Parms{};

	Parms.bEnable = bEnable;
	Parms.cachePath = std::move(cachePath);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetAlphaParameter
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FLinearColor               ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const struct FLinearColor UPVideoPlayer::GetAlphaParameter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetAlphaParameter");

	Params::PVideoPlayer_GetAlphaParameter Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetCurrentPosition
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoPlayer::GetCurrentPosition()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetCurrentPosition");

	Params::PVideoPlayer_GetCurrentPosition Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetDuration
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoPlayer::GetDuration()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetDuration");

	Params::PVideoPlayer_GetDuration Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetMediaType
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoPlayer::GetMediaType()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetMediaType");

	Params::PVideoPlayer_GetMediaType Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetPlayStatus
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoPlayer::GetPlayStatus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetPlayStatus");

	Params::PVideoPlayer_GetPlayStatus Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetRate
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UPVideoPlayer::GetRate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetRate");

	Params::PVideoPlayer_GetRate Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetResolution
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// int32*                                  nWidth                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32*                                  nHeight                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::GetResolution(int32* nWidth, int32* nHeight)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetResolution");

	Params::PVideoPlayer_GetResolution Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (nWidth != nullptr)
		*nWidth = Parms.nWidth;

	if (nHeight != nullptr)
		*nHeight = Parms.nHeight;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetRgbParameter
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FLinearColor               ReturnValue                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

const struct FLinearColor UPVideoPlayer::GetRgbParameter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetRgbParameter");

	Params::PVideoPlayer_GetRgbParameter Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetVideoAlpha
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UPVideoPlayer::GetVideoAlpha()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetVideoAlpha");

	Params::PVideoPlayer_GetVideoAlpha Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetVideoTexture
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nIdx                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UTexture2D*                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UTexture2D* UPVideoPlayer::GetVideoTexture(int32 nIdx)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetVideoTexture");

	Params::PVideoPlayer_GetVideoTexture Parms{};

	Parms.nIdx = nIdx;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetVideoTime
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// float*                                  fCurTime                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float*                                  fTotalTime                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::GetVideoTime(float* fCurTime, float* fTotalTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetVideoTime");

	Params::PVideoPlayer_GetVideoTime Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (fCurTime != nullptr)
		*fCurTime = Parms.fCurTime;

	if (fTotalTime != nullptr)
		*fTotalTime = Parms.fTotalTime;
}


// Function PandoraVideoPlayer.PVideoPlayer.GetYUVFormat
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoPlayer::GetYUVFormat()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "GetYUVFormat");

	Params::PVideoPlayer_GetYUVFormat Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.IsAlphaVideo
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPVideoPlayer::IsAlphaVideo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "IsAlphaVideo");

	Params::PVideoPlayer_IsAlphaVideo Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.IsPause
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPVideoPlayer::IsPause()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "IsPause");

	Params::PVideoPlayer_IsPause Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.IsPlaying
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPVideoPlayer::IsPlaying()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "IsPlaying");

	Params::PVideoPlayer_IsPlaying Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.IsTextureUpdated
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPVideoPlayer::IsTextureUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "IsTextureUpdated");

	Params::PVideoPlayer_IsTextureUpdated Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.Pause
// (Final, Native, Public, BlueprintCallable)

void UPVideoPlayer::Pause()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "Pause");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.Play
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    StrUrl                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bLoop                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoPlayer::Play(const class FString& StrUrl, bool bLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "Play");

	Params::PVideoPlayer_Play Parms{};

	Parms.StrUrl = std::move(StrUrl);
	Parms.bLoop = bLoop;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.PlayOnceAndLoopBetween
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    StrUrl                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   nStartMs                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   nEndMs                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoPlayer::PlayOnceAndLoopBetween(const class FString& StrUrl, int32 nStartMs, int32 nEndMs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "PlayOnceAndLoopBetween");

	Params::PVideoPlayer_PlayOnceAndLoopBetween Parms{};

	Parms.StrUrl = std::move(StrUrl);
	Parms.nStartMs = nStartMs;
	Parms.nEndMs = nEndMs;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.Resume
// (Final, Native, Public, BlueprintCallable)

void UPVideoPlayer::Resume()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "Resume");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.Seek
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nSecond                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::Seek(int32 nSecond)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "Seek");

	Params::PVideoPlayer_Seek Parms{};

	Parms.nSecond = nSecond;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SeekAndPause
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nMilliSec                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SeekAndPause(int32 nMilliSec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SeekAndPause");

	Params::PVideoPlayer_SeekAndPause Parms{};

	Parms.nMilliSec = nMilliSec;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SeekMs
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   millisec                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SeekMs(int32 millisec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SeekMs");

	Params::PVideoPlayer_SeekMs Parms{};

	Parms.millisec = millisec;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetAutoPlay
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bAutoPlay                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetAutoPlay(bool bAutoPlay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SetAutoPlay");

	Params::PVideoPlayer_SetAutoPlay Parms{};

	Parms.bAutoPlay = bAutoPlay;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetDataUpdateCallback
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TScriptInterface<class IPVideoPlayerInterface>dataUpdateInterface                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetDataUpdateCallback(TScriptInterface<class IPVideoPlayerInterface> dataUpdateInterface)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SetDataUpdateCallback");

	Params::PVideoPlayer_SetDataUpdateCallback Parms{};

	Parms.dataUpdateInterface = dataUpdateInterface;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetDecryptionKey
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    decryptionKey                                          (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UPVideoPlayer::SetDecryptionKey(const class FString& decryptionKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SetDecryptionKey");

	Params::PVideoPlayer_SetDecryptionKey Parms{};

	Parms.decryptionKey = std::move(decryptionKey);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetNeedPlayAudio
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bNeedPlayAudio                                         (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetNeedPlayAudio(bool bNeedPlayAudio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SetNeedPlayAudio");

	Params::PVideoPlayer_SetNeedPlayAudio Parms{};

	Parms.bNeedPlayAudio = bNeedPlayAudio;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetNeedVideoTexture
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bNeedVideoTexture                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetNeedVideoTexture(bool bNeedVideoTexture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SetNeedVideoTexture");

	Params::PVideoPlayer_SetNeedVideoTexture Parms{};

	Parms.bNeedVideoTexture = bNeedVideoTexture;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetNextVideo
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    StrUrl                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bLoop                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetNextVideo(const class FString& StrUrl, bool bLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SetNextVideo");

	Params::PVideoPlayer_SetNextVideo Parms{};

	Parms.StrUrl = std::move(StrUrl);
	Parms.bLoop = bLoop;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetOnlyPlayType
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   Type                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetOnlyPlayType(int32 Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SetOnlyPlayType");

	Params::PVideoPlayer_SetOnlyPlayType Parms{};

	Parms.Type = Type;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetRate
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   nRate                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetRate(float nRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SetRate");

	Params::PVideoPlayer_SetRate Parms{};

	Parms.nRate = nRate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetVideoAlpha
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   fAlpha                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetVideoAlpha(float fAlpha)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SetVideoAlpha");

	Params::PVideoPlayer_SetVideoAlpha Parms{};

	Parms.fAlpha = fAlpha;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.SetVolume
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nVolume                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::SetVolume(int32 nVolume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "SetVolume");

	Params::PVideoPlayer_SetVolume Parms{};

	Parms.nVolume = nVolume;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.Update
// (Final, Native, Public, BlueprintCallable)

void UPVideoPlayer::Update()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "Update");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.PVideoPlayer.UseFileDelegate
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bEnable                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPVideoPlayer::UseFileDelegate(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PVideoPlayer", "UseFileDelegate");

	Params::PVideoPlayer_UseFileDelegate Parms{};

	Parms.bEnable = bEnable;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.ClearCacheResource
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    Path                                                   (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::ClearCacheResource(const class FString& Path)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "ClearCacheResource");

	Params::VideoPlayerWidget_ClearCacheResource Parms{};

	Parms.Path = std::move(Path);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.Close
// (Final, Native, Public, BlueprintCallable)

void UVideoPlayerWidget::Close()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "Close");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.EnableCacheResource
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bEnable                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    Path                                                   (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::EnableCacheResource(bool bEnable, const class FString& Path)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "EnableCacheResource");

	Params::VideoPlayerWidget_EnableCacheResource Parms{};

	Parms.bEnable = bEnable;
	Parms.Path = std::move(Path);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.GetCurrentPosition1
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UVideoPlayerWidget::GetCurrentPosition1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "GetCurrentPosition1");

	Params::VideoPlayerWidget_GetCurrentPosition1 Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.GetDuration1
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UVideoPlayerWidget::GetDuration1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "GetDuration1");

	Params::VideoPlayerWidget_GetDuration1 Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.GetPlayStatus1
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UVideoPlayerWidget::GetPlayStatus1()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "GetPlayStatus1");

	Params::VideoPlayerWidget_GetPlayStatus1 Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.GetVideoAlpha
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float UVideoPlayerWidget::GetVideoAlpha()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "GetVideoAlpha");

	Params::VideoPlayerWidget_GetVideoAlpha Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.OnPlayerEvent
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   EventCode                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   nParam1                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   nParam2                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    strMsg                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::OnPlayerEvent(int32 EventCode, int32 nParam1, int32 nParam2, const class FString& strMsg)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "OnPlayerEvent");

	Params::VideoPlayerWidget_OnPlayerEvent Parms{};

	Parms.EventCode = EventCode;
	Parms.nParam1 = nParam1;
	Parms.nParam2 = nParam2;
	Parms.strMsg = std::move(strMsg);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.Pause
// (Final, Native, Public, BlueprintCallable)

void UVideoPlayerWidget::Pause()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "Pause");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.Play1
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    StrUrl                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bLoop                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UVideoPlayerWidget::Play1(const class FString& StrUrl, bool bLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "Play1");

	Params::VideoPlayerWidget_Play1 Parms{};

	Parms.StrUrl = std::move(StrUrl);
	Parms.bLoop = bLoop;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.PlayOnceAndLoopBetween
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    StrUrl                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   nStartMs                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   nEndMs                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UVideoPlayerWidget::PlayOnceAndLoopBetween(const class FString& StrUrl, int32 nStartMs, int32 nEndMs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "PlayOnceAndLoopBetween");

	Params::VideoPlayerWidget_PlayOnceAndLoopBetween Parms{};

	Parms.StrUrl = std::move(StrUrl);
	Parms.nStartMs = nStartMs;
	Parms.nEndMs = nEndMs;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.PlayWithFd
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nFd                                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bLoop                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UVideoPlayerWidget::PlayWithFd(int32 nFd, bool bLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "PlayWithFd");

	Params::VideoPlayerWidget_PlayWithFd Parms{};

	Parms.nFd = nFd;
	Parms.bLoop = bLoop;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.Resume
// (Final, Native, Public, BlueprintCallable)

void UVideoPlayerWidget::Resume()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "Resume");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.Seek
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nSecond                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::Seek(int32 nSecond)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "Seek");

	Params::VideoPlayerWidget_Seek Parms{};

	Parms.nSecond = nSecond;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SeekAndPause
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nMilliSec                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SeekAndPause(int32 nMilliSec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SeekAndPause");

	Params::VideoPlayerWidget_SeekAndPause Parms{};

	Parms.nMilliSec = nMilliSec;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SeekMs
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nMilliSec                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SeekMs(int32 nMilliSec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SeekMs");

	Params::VideoPlayerWidget_SeekMs Parms{};

	Parms.nMilliSec = nMilliSec;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetAutoPlay
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    doAutoPlay                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetAutoPlay(bool doAutoPlay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetAutoPlay");

	Params::VideoPlayerWidget_SetAutoPlay Parms{};

	Parms.doAutoPlay = doAutoPlay;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetDataUpdateCallback
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// TScriptInterface<class IPVideoPlayerInterface>dataUpdateInterface                                    (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetDataUpdateCallback(TScriptInterface<class IPVideoPlayerInterface> dataUpdateInterface)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetDataUpdateCallback");

	Params::VideoPlayerWidget_SetDataUpdateCallback Parms{};

	Parms.dataUpdateInterface = dataUpdateInterface;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetDecryptionKey
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    decryptionKey                                          (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 UVideoPlayerWidget::SetDecryptionKey(const class FString& decryptionKey)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetDecryptionKey");

	Params::VideoPlayerWidget_SetDecryptionKey Parms{};

	Parms.decryptionKey = std::move(decryptionKey);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetHardwareDecodec
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bHardWare                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetHardwareDecodec(bool bHardWare)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetHardwareDecodec");

	Params::VideoPlayerWidget_SetHardwareDecodec Parms{};

	Parms.bHardWare = bHardWare;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetNeedPlayAudio
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    needPlayAudio                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetNeedPlayAudio(bool needPlayAudio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetNeedPlayAudio");

	Params::VideoPlayerWidget_SetNeedPlayAudio Parms{};

	Parms.needPlayAudio = needPlayAudio;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetNeedVideoTexture
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    needVideoTexture                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetNeedVideoTexture(bool needVideoTexture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetNeedVideoTexture");

	Params::VideoPlayerWidget_SetNeedVideoTexture Parms{};

	Parms.needVideoTexture = needVideoTexture;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetNextVideo
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// const class FString&                    StrUrl                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bLoop                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetNextVideo(const class FString& StrUrl, bool bLoop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetNextVideo");

	Params::VideoPlayerWidget_SetNextVideo Parms{};

	Parms.StrUrl = std::move(StrUrl);
	Parms.bLoop = bLoop;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetOnlyPlayType
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   Type                                                   (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetOnlyPlayType(int32 Type)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetOnlyPlayType");

	Params::VideoPlayerWidget_SetOnlyPlayType Parms{};

	Parms.Type = Type;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetRate
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   nRate                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetRate(float nRate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetRate");

	Params::VideoPlayerWidget_SetRate Parms{};

	Parms.nRate = nRate;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetStopAsyn
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   stopAsyn                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetStopAsyn(int32 stopAsyn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetStopAsyn");

	Params::VideoPlayerWidget_SetStopAsyn Parms{};

	Parms.stopAsyn = stopAsyn;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetVideoAlpha
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   fAlpha                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetVideoAlpha(float fAlpha)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetVideoAlpha");

	Params::VideoPlayerWidget_SetVideoAlpha Parms{};

	Parms.fAlpha = fAlpha;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.SetVolume
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   nVolume                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::SetVolume(int32 nVolume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "SetVolume");

	Params::VideoPlayerWidget_SetVolume Parms{};

	Parms.nVolume = nVolume;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function PandoraVideoPlayer.VideoPlayerWidget.UseFileDelegate
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    bEnable                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UVideoPlayerWidget::UseFileDelegate(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VideoPlayerWidget", "UseFileDelegate");

	Params::VideoPlayerWidget_UseFileDelegate Parms{};

	Parms.bEnable = bEnable;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
