#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerfCat

#include "Basic.hpp"

#include "PerfCat_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function PerfCat.PerfEventSubsystem.GetRunningStatus
// 0x0001 (0x0001 - 0x0000)
struct PerfEventSubsystem_GetRunningStatus final
{
public:
	EPerfEventProfilerRunningStatus               ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PerfEventSubsystem_GetRunningStatus;

// Function PerfCat.MemoryBlackHole.AllocateMemory
// 0x0004 (0x0004 - 0x0000)
struct MemoryBlackHole_AllocateMemory final
{
public:
	int32                                         SizeInMB;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MemoryBlackHole_AllocateMemory;

// Function PerfCat.MemoryBlackHole.GraduallyAllocateMemory
// 0x0008 (0x0008 - 0x0000)
struct MemoryBlackHole_GraduallyAllocateMemory final
{
public:
	int32                                         ChunkSizeInMB;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TimeBetweenChunks;                                 // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_MemoryBlackHole_GraduallyAllocateMemory;

// Function PerfCat.PerfCatFunctionLibrary.AllocateMemory
// 0x0004 (0x0004 - 0x0000)
struct PerfCatFunctionLibrary_AllocateMemory final
{
public:
	int32                                         SizeInMB;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PerfCatFunctionLibrary_AllocateMemory;

// Function PerfCat.PerfCatFunctionLibrary.GraduallyAllocateMemory
// 0x0008 (0x0008 - 0x0000)
struct PerfCatFunctionLibrary_GraduallyAllocateMemory final
{
public:
	int32                                         ChunkSizeInMB;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TimeBetweenChunks;                                 // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PerfCatFunctionLibrary_GraduallyAllocateMemory;

// Function PerfCat.PerfCatFunctionLibrary.SetViewMode
// 0x0010 (0x0010 - 0x0000)
struct PerfCatFunctionLibrary_SetViewMode final
{
public:
	class FString                                 ViewMode;                                          // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_PerfCatFunctionLibrary_SetViewMode;

// Function PerfCat.PerfCatFunctionLibrary.SpawnBlackHole
// 0x0010 (0x0010 - 0x0000)
struct PerfCatFunctionLibrary_SpawnBlackHole final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_PerfCatFunctionLibrary_SpawnBlackHole;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
