#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PerfDogExtension

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class PerfDogExtension.PerfDogExtensionSubsystem
// 0x0050 (0x0080 - 0x0030)
class UPerfDogExtensionSubsystem final : public UGameInstanceSubsystem
{
public:
	uint8                                         Pad_30[0x50];                                      // 0x0030(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PerfDogExtensionSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PerfDogExtensionSubsystem")
	}
	static class UPerfDogExtensionSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPerfDogExtensionSubsystem>();
	}
};
DUMPER7_ASSERTS_UPerfDogExtensionSubsystem;

// Class PerfDogExtension.PerfDogFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UPerfDogFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void AddNote(const class FString& InNote);
	static void DisablePerfDogExtension();
	static void EnablePerfDogExtension();
	static bool IsCategoryRegistered(const class FString& CategoryName);
	static void PostFloatValue(const class FString& Category, const class FString& Key, float Value);
	static void PostIntValue(const class FString& Category, const class FString& Key, int32 Value);
	static void PostPlayerPosition(const class FString& Category, const struct FVector& position);
	static bool RegisterCategory(const class FString& CategoryName, const class FString& AggregationType, float TimeInterval, bool bEnabledInShipping);
	static void SetLabel(const class FString& InLabel);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PerfDogFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PerfDogFunctionLibrary")
	}
	static class UPerfDogFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPerfDogFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UPerfDogFunctionLibrary;

// Class PerfDogExtension.PerfDogTestLibrary
// 0x0000 (0x0028 - 0x0028)
class UPerfDogTestLibrary final : public UBlueprintFunctionLibrary
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PerfDogTestLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PerfDogTestLibrary")
	}
	static class UPerfDogTestLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPerfDogTestLibrary>();
	}
};
DUMPER7_ASSERTS_UPerfDogTestLibrary;

SDK_NAMESPACE_END
