#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlatformImageTool

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "PlatformImageTool_structs.hpp"
#include "CoreUObject_classes.hpp"


SDK_NAMESPACE_START

// Class PlatformImageTool.PlatformImageLibrary
// 0x0000 (0x0028 - 0x0028)
class UPlatformImageLibrary final : public UBlueprintFunctionLibrary
{
public:
	static bool CaptureSceneFinalImmediately(class USceneCaptureComponent2D* SceneCaptureComponent, class UTextureRenderTarget2D* RenderTarget);
	static class UTextureRenderTarget2D* CreateRenderTarget2D(class UWorld* World, const class FString& Prefix, ETextureRenderTargetFormat Format, int32 PixelWidth, int32 PixelHeight);
	static class UTextureRenderTarget2D* CreateRenderTargetMatchingBackBuffer(class UWorld* World, const class FString& Prefix, int32 PixelWidth, int32 PixelHeight);
	static class UTexture2D* CreateScalableTexture2DByFile(const class FString& ImagePath, const class FString& Prefix, int32 ScaledHeight);
	static class UTexture2D* CreateScalableTexture2DBySerializedRenderTarget(class UTextureRenderTarget2D* RenderTarget, const class FString& SaveImagePath, const class FString& Prefix, int32 ScaledHeight, bool bShouldFlipImageVertically);
	static class UTexture2DDynamic* CreateTextureFromBase64Data(const class FString& Base64Data);
	static bool ExportRenderTarget(class UTextureRenderTarget2D* RenderTarget, const class FString& SaveImagePath, bool bShouldFlipImageVertically);
	static bool GetTexture2DSizeByFile(const class FString& ImagePath, struct FIntPoint* OutSize);
	static class FString SaveImageToAlbum(const class FString& ImagePath);
	static bool SaveTextureAsFile(class UWorld* World, class UTexture2D* Texture, const struct FVector2D& InSize, const struct FVector2D& InUV0, const struct FVector2D& InUV1, const class FString& ImagePath);
	static bool SaveTextureAsFile1(class UTexture2D* Texture, const class FString& ImagePath);
	static bool SaveUserWidgetToImage(class UWorld* World, class UUserWidget* Widget, const class FString& SaveImagePath, bool bFullScreen, float Scale);
	static bool SaveUserWidgetToImageByCustomSize(class UWorld* World, class UUserWidget* Widget, const class FString& SaveImagePath, const struct FVector2D& DesiredSize);
	static bool SaveWidgetToImage(class UWorld* World, class UWidget* Widget, const class FString& SaveImagePath, bool bFullScreen, float Scale);
	static void UpdateRenderTarget(class UTextureRenderTarget2D* RenderTarget, bool bClearRT);
	static bool UpdateTexture2DByFile(class UTexture2D* Texture2D, const class FString& ImagePath);
	static bool ValidateSignatureBase64(const class FString& PublicKeyPEM, const class FString& SignatureBase64, const class FString& OriginalText);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("PlatformImageLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlatformImageLibrary")
	}
	static class UPlatformImageLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlatformImageLibrary>();
	}
};
DUMPER7_ASSERTS_UPlatformImageLibrary;

// Class PlatformImageTool.QRCodeGenerator
// 0x0048 (0x0070 - 0x0028)
class UQRCodeGenerator final : public UObject
{
public:
	uint8                                         Pad_28[0x8];                                       // 0x0028(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Version;                                           // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	EQrEcc                                        EccLevel;                                          // 0x0034(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<uint8>                                 DataCodeWords;                                     // 0x0038(0x0010)(ZeroConstructor, NativeAccessSpecifierPrivate)
	uint8                                         Pad_48[0x20];                                      // 0x0048(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             QRCodeTexture;                                     // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void DisplayQRToTexture();
	void DrawCodewords(const TArray<uint8>& Data);
	class UQRCodeGenerator* EncodeSegments(const TArray<class UQrSegment*>& Segments, EQrEcc Level, int32 MinVersion, int32 MaxVersion, int32 Mask, bool bBoostEcl);
	class UQRCodeGenerator* EncodeText(EQrEcc EccLevl, const class FString& TextToEncode);
	void Initialize(int32 NewVersion, EQrEcc Level, const TArray<uint8>& NewDataCodewords, int32 NewMaskPattern);

	TArray<uint8> GetQRBinary() const;
	uint8 GetSize() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("QRCodeGenerator")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QRCodeGenerator")
	}
	static class UQRCodeGenerator* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQRCodeGenerator>();
	}
};
DUMPER7_ASSERTS_UQRCodeGenerator;

// Class PlatformImageTool.QrSegment
// 0x0050 (0x0078 - 0x0028)
class UQrSegment final : public UObject
{
public:
	uint8                                         Pad_28[0x10];                                      // 0x0028(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	struct FQrMode                                Mode;                                              // 0x0038(0x0018)(NativeAccessSpecifierPublic)
	int32                                         CharacterCount;                                    // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 Data;                                              // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<bool>                                  RawData;                                           // 0x0068(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)

public:
	static int32 GetTotalBits(const TArray<class UQrSegment*>& Segs, int32 Version);
	static TArray<class UQrSegment*> MakeSegments(const class FString& text);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("QrSegment")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QrSegment")
	}
	static class UQrSegment* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQrSegment>();
	}
};
DUMPER7_ASSERTS_UQrSegment;

// Class PlatformImageTool.RenderTextureService
// 0x0018 (0x0040 - 0x0028)
class URenderTextureService final : public UObject
{
public:
	uint8                                         Pad_28[0x18];                                      // 0x0028(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void CancelTask(ERenderTextureTask TaskType);
	ERenderTextureTask MakeThumbnailSerializeTask(class UTextureRenderTarget2D* TexRT, int32 ThumbnailScaledHeight, const class FString& ImageSavePath, const class FString& ThumbnailSavePath, const class FString& TexturePrefix, TDelegate<void(class URenderTextureService* Service, class UTexture2D* Texture)> ThumbnailDelegate, TDelegate<void(class URenderTextureService* Service, const class FString& Path, const class FString& FileMD5)> SerializedDelegate, bool bInEnableAsyncRHIFeedback, bool bEnableGPUCopyTextureReadBack);
	ERenderTextureTask MakeThumbnailSerializeTaskByBuffer(const TArray<uint8>& Buffer, int32 ThumbnailScaledHeight, const class FString& ImageSavePath, const class FString& ThumbnailSavePath, const class FString& TexturePrefix, TDelegate<void(class URenderTextureService* Service, class UTexture2D* Texture)> ThumbnailDelegate, TDelegate<void(class URenderTextureService* Service, const class FString& Path, const class FString& FileMD5)> SerializedDelegate);
	ERenderTextureTask MakeThumbnailSerializeTaskByFile(const class FString& FilePath, int32 ThumbnailScaledHeight, const class FString& ImageSavePath, const class FString& ThumbnailSavePath, const class FString& TexturePrefix, TDelegate<void(class URenderTextureService* Service, class UTexture2D* Texture)> ThumbnailDelegate, TDelegate<void(class URenderTextureService* Service, const class FString& Path, const class FString& FileMD5)> SerializedDelegate);
	ERenderTextureTask MakeThumbnailSerializeTaskByHttp(class USimpleHttpService* HTTP, int32 ThumbnailScaledHeight, const class FString& ImageSavePath, const class FString& ThumbnailSavePath, const class FString& TexturePrefix, TDelegate<void(class URenderTextureService* Service, class UTexture2D* Texture)> ThumbnailDelegate, TDelegate<void(class URenderTextureService* Service, const class FString& Path, const class FString& FileMD5)> SerializedDelegate);
	void StartTask(ERenderTextureTask TaskType);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RenderTextureService")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RenderTextureService")
	}
	static class URenderTextureService* GetDefaultObj()
	{
		return GetDefaultObjImpl<URenderTextureService>();
	}
};
DUMPER7_ASSERTS_URenderTextureService;

// Class PlatformImageTool.TakePhotoFile
// 0x00E0 (0x0108 - 0x0028)
class UTakePhotoFile final : public UObject
{
public:
	uint8                                         Pad_28[0x8];                                       // 0x0028(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class UTakePhotoFile* File, bool bSuccess)> OnPhotoFileDataLoaded; // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	ETakePhotoFileStatus                          ReadonlyStatus;                                    // 0x0040(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ReadonlyFileMd5;                                   // 0x0048(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReadonlyFilePath;                                  // 0x0058(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReadonlyFileWidth;                                 // 0x0068(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReadonlyFileHeight;                                // 0x006C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReadonlyRawFileWidth;                              // 0x0070(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReadonlyRawFileHeight;                             // 0x0074(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReadonlyPhotoFormat;                               // 0x0078(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReadonlyPixelFormat;                               // 0x007C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReadonlyRGBFormat;                                 // 0x0080(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             DesiredDisplayTarget;                              // 0x0088(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTakePhotoFile*                         DesiredThumbnailFile;                              // 0x0090(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReadonlyClipPhotoFilePath;                         // 0x0098(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReadonlyClipDesiredWidth;                          // 0x00A8(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReadonlyClipDesiredHeight;                         // 0x00AC(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReadonlyClipDesiredQuality;                        // 0x00B0(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_B4[0x4];                                       // 0x00B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ReadonlyClipFileMd5;                               // 0x00B8(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bInputNeedThumbnailMd5;                            // 0x00C8(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableGenMips;                                    // 0x00C9(0x0001)(ZeroConstructor, Transient, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_CA[0x6];                                       // 0x00CA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 ReadonlyThumbnailMd5;                              // 0x00D0(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E0[0x28];                                      // 0x00E0(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool AsyncLoadFromFilePath(const class FString& FilePath, const class FString& FileDesiredMd5, int32 ThumbnailFileHeight, const class FString& ThumbnailPath);
	class UTexture2D* CreateUpdatedTexture2D(const class FString& Prefix);
	void DiscardDataImmediately();
	int32 GetBytes();
	void ReleaseResources();
	void RequestClipPhotoFileBeforeLoad(const class FString& ClipPhotoFilePath, int32 DesiredWidth, int32 DesiredHeight, int32 DesiredQuality);
	bool SetUpdateDesiredTexture(class UTexture2D* Texture2D);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("TakePhotoFile")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TakePhotoFile")
	}
	static class UTakePhotoFile* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTakePhotoFile>();
	}
};
DUMPER7_ASSERTS_UTakePhotoFile;

SDK_NAMESPACE_END
