#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RocoRootMotion

#include "Basic.hpp"

#include "RocoRootMotion_classes.hpp"
#include "RocoRootMotion_parameters.hpp"


SDK_NAMESPACE_START

// Function RocoRootMotion.RootMotionMovement.BeginOverlap
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// class ARootMotionGuide*                 RootMotionGuide                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bIsAutoTrigger                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URootMotionMovement::BeginOverlap(class ARootMotionGuide* RootMotionGuide, bool* bIsAutoTrigger)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "BeginOverlap");

	Params::RootMotionMovement_BeginOverlap Parms{};

	Parms.RootMotionGuide = RootMotionGuide;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bIsAutoTrigger != nullptr)
		*bIsAutoTrigger = Parms.bIsAutoTrigger;
}


// Function RocoRootMotion.RootMotionMovement.BeginRootMotion
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// bool*                                   bResult                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class ARootMotionGuide**                RootMotionGuide                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URootMotionMovement::BeginRootMotion(bool* bResult, class ARootMotionGuide** RootMotionGuide)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "BeginRootMotion");

	Params::RootMotionMovement_BeginRootMotion Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bResult != nullptr)
		*bResult = Parms.bResult;

	if (RootMotionGuide != nullptr)
		*RootMotionGuide = Parms.RootMotionGuide;
}


// Function RocoRootMotion.RootMotionMovement.BeginRootMotionNetwork
// (Final, Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const class FString&                    RootMotionGuideName                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bResult                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class ARootMotionGuide**                RootMotionGuide                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URootMotionMovement::BeginRootMotionNetwork(const class FString& RootMotionGuideName, bool* bResult, class ARootMotionGuide** RootMotionGuide)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "BeginRootMotionNetwork");

	Params::RootMotionMovement_BeginRootMotionNetwork Parms{};

	Parms.RootMotionGuideName = std::move(RootMotionGuideName);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bResult != nullptr)
		*bResult = Parms.bResult;

	if (RootMotionGuide != nullptr)
		*RootMotionGuide = Parms.RootMotionGuide;
}


// Function RocoRootMotion.RootMotionMovement.EndOverlap
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class ARootMotionGuide*                 RootMotionGuide                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URootMotionMovement::EndOverlap(class ARootMotionGuide* RootMotionGuide)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "EndOverlap");

	Params::RootMotionMovement_EndOverlap Parms{};

	Parms.RootMotionGuide = RootMotionGuide;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RocoRootMotion.RootMotionMovement.EndRootMotion
// (Final, Native, Public, BlueprintCallable)

void URootMotionMovement::EndRootMotion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "EndRootMotion");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function RocoRootMotion.RootMotionMovement.SetCurrentOverlappedRootMotionGuide
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class ARootMotionGuide*                 RootMotionGuide                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URootMotionMovement::SetCurrentOverlappedRootMotionGuide(class ARootMotionGuide* RootMotionGuide)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "SetCurrentOverlappedRootMotionGuide");

	Params::RootMotionMovement_SetCurrentOverlappedRootMotionGuide Parms{};

	Parms.RootMotionGuide = RootMotionGuide;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RocoRootMotion.RootMotionMovement.UpdateRootMotion
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// float                                   DeltaTime                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URootMotionMovement::UpdateRootMotion(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "UpdateRootMotion");

	Params::RootMotionMovement_UpdateRootMotion Parms{};

	Parms.DeltaTime = DeltaTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RocoRootMotion.RootMotionMovement.FindRootMotionGuide
// (Final, Native, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FVector&                   MovementDirection                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// ERootMotionGuideTriggerType             TriggerType                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   MinimumDotValue                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool*                                   bFound                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class ARootMotionGuide**                RootMotionGuide                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URootMotionMovement::FindRootMotionGuide(const struct FVector& MovementDirection, ERootMotionGuideTriggerType TriggerType, float MinimumDotValue, bool* bFound, class ARootMotionGuide** RootMotionGuide) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "FindRootMotionGuide");

	Params::RootMotionMovement_FindRootMotionGuide Parms{};

	Parms.MovementDirection = std::move(MovementDirection);
	Parms.TriggerType = TriggerType;
	Parms.MinimumDotValue = MinimumDotValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bFound != nullptr)
		*bFound = Parms.bFound;

	if (RootMotionGuide != nullptr)
		*RootMotionGuide = Parms.RootMotionGuide;
}


// Function RocoRootMotion.RootMotionMovement.FindRootMotionGuideToAutoPlay
// (Final, Native, Public, HasOutParams, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool*                                   bFound                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class ARootMotionGuide**                RootMotionGuide                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URootMotionMovement::FindRootMotionGuideToAutoPlay(bool* bFound, class ARootMotionGuide** RootMotionGuide) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "FindRootMotionGuideToAutoPlay");

	Params::RootMotionMovement_FindRootMotionGuideToAutoPlay Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (bFound != nullptr)
		*bFound = Parms.bFound;

	if (RootMotionGuide != nullptr)
		*RootMotionGuide = Parms.RootMotionGuide;
}


// Function RocoRootMotion.RootMotionMovement.HasOverlappedRootMotionGuide
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool URootMotionMovement::HasOverlappedRootMotionGuide() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "HasOverlappedRootMotionGuide");

	Params::RootMotionMovement_HasOverlappedRootMotionGuide Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionMovement.IsPlayingRootMotion
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool URootMotionMovement::IsPlayingRootMotion() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "IsPlayingRootMotion");

	Params::RootMotionMovement_IsPlayingRootMotion Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionMovement.IsPlayingWith
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class ARootMotionGuide*                 RootMotionGuide                                        (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool URootMotionMovement::IsPlayingWith(class ARootMotionGuide* RootMotionGuide) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "IsPlayingWith");

	Params::RootMotionMovement_IsPlayingWith Parms{};

	Parms.RootMotionGuide = RootMotionGuide;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionMovement.IsPlayingWithCurrentOverlappedRootMotionGuide
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool URootMotionMovement::IsPlayingWithCurrentOverlappedRootMotionGuide() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionMovement", "IsPlayingWithCurrentOverlappedRootMotionGuide");

	Params::RootMotionMovement_IsPlayingWithCurrentOverlappedRootMotionGuide Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.NavLinkProxyForRootMotionGuides.UpdateSmartLink
// (Final, Native, Public)

void ANavLinkProxyForRootMotionGuides::UpdateSmartLink()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NavLinkProxyForRootMotionGuides", "UpdateSmartLink");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function RocoRootMotion.RocoTransformCurve.AddTransformValue
// (Final, Native, Public, HasDefaults, BlueprintCallable)
// Parameters:
// const struct FTransform&                Value                                                  (Parm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
// float                                   InTime                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URocoTransformCurve::AddTransformValue(const struct FTransform& Value, float InTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RocoTransformCurve", "AddTransformValue");

	Params::RocoTransformCurve_AddTransformValue Parms{};

	Parms.Value = std::move(Value);
	Parms.InTime = InTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RocoRootMotion.RocoTransformCurve.GetTransformValue
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// float                                   InTime                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FTransform                       ReturnValue                                            (Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FTransform URocoTransformCurve::GetTransformValue(float InTime) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RocoTransformCurve", "GetTransformValue");

	Params::RocoTransformCurve_GetTransformValue Parms{};

	Parms.InTime = InTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionGuide.BeginOverlap
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ARootMotionGuide::BeginOverlap(class ACharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "BeginOverlap");

	Params::RootMotionGuide_BeginOverlap Parms{};

	Parms.Character = Character;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RocoRootMotion.RootMotionGuide.EndOverlap
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ARootMotionGuide::EndOverlap(class ACharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "EndOverlap");

	Params::RootMotionGuide_EndOverlap Parms{};

	Parms.Character = Character;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RocoRootMotion.RootMotionGuide.OnBeginRootMotion
// (Event, Public, BlueprintEvent)
// Parameters:
// class ACharacter*                       Character                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ARootMotionGuide::OnBeginRootMotion(class ACharacter* Character)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "OnBeginRootMotion");

	Params::RootMotionGuide_OnBeginRootMotion Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RocoRootMotion.RootMotionGuide.ReceiveInitializeSubTrigger
// (Event, Protected, BlueprintEvent)
// Parameters:
// const class ARootMotionGuide*           MainTrigger                                            (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ARootMotionGuide::ReceiveInitializeSubTrigger(const class ARootMotionGuide* MainTrigger)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "ReceiveInitializeSubTrigger");

	Params::RootMotionGuide_ReceiveInitializeSubTrigger Parms{};

	Parms.MainTrigger = MainTrigger;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RocoRootMotion.RootMotionGuide.CanPlayRootMotionMontage
// (Native, Event, Public, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class ACharacter*                       Character                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class URootMotionMovement*        RootMotionMovement                                     (ConstParm, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool ARootMotionGuide::CanPlayRootMotionMontage(class ACharacter* Character, const class URootMotionMovement* RootMotionMovement) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "CanPlayRootMotionMontage");

	Params::RootMotionGuide_CanPlayRootMotionMontage Parms{};

	Parms.Character = Character;
	Parms.RootMotionMovement = RootMotionMovement;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionGuide.GetMovementDirectionInWorld
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector ARootMotionGuide::GetMovementDirectionInWorld() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "GetMovementDirectionInWorld");

	Params::RootMotionGuide_GetMovementDirectionInWorld Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionGuide.GetRootMotionAnimMontage
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// class UAnimMontage*                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UAnimMontage* ARootMotionGuide::GetRootMotionAnimMontage() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "GetRootMotionAnimMontage");

	Params::RootMotionGuide_GetRootMotionAnimMontage Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionGuide.GetRootMotionDirection
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector ARootMotionGuide::GetRootMotionDirection() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "GetRootMotionDirection");

	Params::RootMotionGuide_GetRootMotionDirection Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionGuide.GetRootMotionLocation
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FVector                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

struct FVector ARootMotionGuide::GetRootMotionLocation() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "GetRootMotionLocation");

	Params::RootMotionGuide_GetRootMotionLocation Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionGuide.GetRootMotionNextMovementMode
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// EMovementMode                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

EMovementMode ARootMotionGuide::GetRootMotionNextMovementMode() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "GetRootMotionNextMovementMode");

	Params::RootMotionGuide_GetRootMotionNextMovementMode Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionGuide.GetRootMotionRotation
// (Final, Native, Public, HasDefaults, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// struct FRotator                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)

struct FRotator ARootMotionGuide::GetRootMotionRotation() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuide", "GetRootMotionRotation");

	Params::RootMotionGuide_GetRootMotionRotation Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionGuidePathFollowing.StartPathFollowing
// (Final, Native, Public, BlueprintCallable)

void URootMotionGuidePathFollowing::StartPathFollowing()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuidePathFollowing", "StartPathFollowing");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function RocoRootMotion.RootMotionGuideSmartLinkFilter.IsLinkPathfindingAllowed
// (Native, Event, Public, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const class UObject*                    Querier                                                (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool IRootMotionGuideSmartLinkFilter::IsLinkPathfindingAllowed(const class UObject* Querier) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("RootMotionGuideSmartLinkFilter", "IsLinkPathfindingAllowed");

	Params::RootMotionGuideSmartLinkFilter_IsLinkPathfindingAllowed Parms{};

	Parms.Querier = Querier;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	AsUObject()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoRootMotion.RootMotionGuideWithSmartLink.ReceiveSmartLinkReached
// (Event, Public, HasOutParams, HasDefaults, BlueprintEvent)
// Parameters:
// class AActor*                           Agent                                                  (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const struct FVector&                   Destination                                            (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void ARootMotionGuideWithSmartLink::ReceiveSmartLinkReached(class AActor* Agent, const struct FVector& Destination)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuideWithSmartLink", "ReceiveSmartLinkReached");

	Params::RootMotionGuideWithSmartLink_ReceiveSmartLinkReached Parms{};

	Parms.Agent = Agent;
	Parms.Destination = std::move(Destination);

	UObject::ProcessEvent(Func, &Parms);
}


// Function RocoRootMotion.RootMotionGuideWithSmartLink.UpdateSmartLink
// (Final, Native, Public)

void ARootMotionGuideWithSmartLink::UpdateSmartLink()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RootMotionGuideWithSmartLink", "UpdateSmartLink");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
