#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RocoSequenceDlc

#include "Basic.hpp"

#include "RocoSequenceDlc_classes.hpp"
#include "RocoSequenceDlc_parameters.hpp"


SDK_NAMESPACE_START

// Function RocoSequenceDlc.RocoSequenceDlcLibrary.GetPlayPositionInMS
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// const int32                             SessionId                                              (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 URocoSequenceDlcLibrary::GetPlayPositionInMS(const int32 SessionId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "GetPlayPositionInMS");

	Params::RocoSequenceDlcLibrary_GetPlayPositionInMS Parms{};

	Parms.SessionId = SessionId;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.GetSequenceAudioId
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 URocoSequenceDlcLibrary::GetSequenceAudioId()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "GetSequenceAudioId");

	Params::RocoSequenceDlcLibrary_GetSequenceAudioId Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.GetSequenceAudioLength
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float URocoSequenceDlcLibrary::GetSequenceAudioLength()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "GetSequenceAudioLength");

	Params::RocoSequenceDlcLibrary_GetSequenceAudioLength Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.GetSequenceAudioSessionId
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 URocoSequenceDlcLibrary::GetSequenceAudioSessionId()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "GetSequenceAudioSessionId");

	Params::RocoSequenceDlcLibrary_GetSequenceAudioSessionId Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.GetSequenceAudioSource
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString URocoSequenceDlcLibrary::GetSequenceAudioSource()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "GetSequenceAudioSource");

	Params::RocoSequenceDlcLibrary_GetSequenceAudioSource Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.GetSequenceAudioState
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString URocoSequenceDlcLibrary::GetSequenceAudioState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "GetSequenceAudioState");

	Params::RocoSequenceDlcLibrary_GetSequenceAudioState Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.GetSequenceAudioStateGroup
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString URocoSequenceDlcLibrary::GetSequenceAudioStateGroup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "GetSequenceAudioStateGroup");

	Params::RocoSequenceDlcLibrary_GetSequenceAudioStateGroup Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.GetSequenceBgmId
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 URocoSequenceDlcLibrary::GetSequenceBgmId()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "GetSequenceBgmId");

	Params::RocoSequenceDlcLibrary_GetSequenceBgmId Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.GetSequenceBgmLength
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

float URocoSequenceDlcLibrary::GetSequenceBgmLength()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "GetSequenceBgmLength");

	Params::RocoSequenceDlcLibrary_GetSequenceBgmLength Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.GetSequenceBgmSessionId
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// int32                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

int32 URocoSequenceDlcLibrary::GetSequenceBgmSessionId()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "GetSequenceBgmSessionId");

	Params::RocoSequenceDlcLibrary_GetSequenceBgmSessionId Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.IsMaterialValidInUnionTrack
// (Final, Native, Static, Public, HasOutParams, BlueprintCallable)
// Parameters:
// const class UMaterialInterface*         Material                                               (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const TArray<class FName>&              FilterMaterialNames                                    (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool URocoSequenceDlcLibrary::IsMaterialValidInUnionTrack(const class UMaterialInterface* Material, const TArray<class FName>& FilterMaterialNames)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "IsMaterialValidInUnionTrack");

	Params::RocoSequenceDlcLibrary_IsMaterialValidInUnionTrack Parms{};

	Parms.Material = Material;
	Parms.FilterMaterialNames = std::move(FilterMaterialNames);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.PlaySequenceAudio
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// int32                                   AudioId                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URocoSequenceDlcLibrary::PlaySequenceAudio(int32 AudioId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "PlaySequenceAudio");

	Params::RocoSequenceDlcLibrary_PlaySequenceAudio Parms{};

	Parms.AudioId = AudioId;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.PlaySequenceBgm
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// int32                                   AudioId                                                (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URocoSequenceDlcLibrary::PlaySequenceBgm(int32 AudioId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "PlaySequenceBgm");

	Params::RocoSequenceDlcLibrary_PlaySequenceBgm Parms{};

	Parms.AudioId = AudioId;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.ReleaseAudioAndBgmSession
// (Final, Native, Static, Private, BlueprintCallable)

void URocoSequenceDlcLibrary::ReleaseAudioAndBgmSession()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "ReleaseAudioAndBgmSession");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.ReleaseSession
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// const int32                             SessionId                                              (ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bStopEvent                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    Source                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    bForceBurn                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// float                                   FadeOutTime                                            (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URocoSequenceDlcLibrary::ReleaseSession(const int32 SessionId, bool bStopEvent, const class FString& Source, bool bForceBurn, float FadeOutTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("RocoSequenceDlcLibrary", "ReleaseSession");

	Params::RocoSequenceDlcLibrary_ReleaseSession Parms{};

	Parms.SessionId = SessionId;
	Parms.bStopEvent = bStopEvent;
	Parms.Source = std::move(Source);
	Parms.bForceBurn = bForceBurn;
	Parms.FadeOutTime = FadeOutTime;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// Function RocoSequenceDlc.RocoSequenceDlcLibrary.SetAudioState
// (Final, Native, Private, BlueprintCallable)
// Parameters:
// const class FString&                    StateGroup                                             (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    State                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// const class FString&                    Source                                                 (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void URocoSequenceDlcLibrary::SetAudioState(const class FString& StateGroup, const class FString& State, const class FString& Source)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("RocoSequenceDlcLibrary", "SetAudioState");

	Params::RocoSequenceDlcLibrary_SetAudioState Parms{};

	Parms.StateGroup = std::move(StateGroup);
	Parms.State = std::move(State);
	Parms.Source = std::move(Source);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


SDK_NAMESPACE_END
