#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RocoAnimExtension

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function RocoAnimExtension.CheckCurrentAnimationBPLibrary.CheckRibbonAnimation
// 0x0048 (0x0048 - 0x0000)
struct CheckCurrentAnimationBPLibrary_CheckRibbonAnimation final
{
public:
	TArray<class FString>                         OutNames;                                          // 0x0000(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<class UAnimSequenceBase*>              sequences;                                         // 0x0010(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<class UBlendSpaceBase*>                blendSpaces;                                       // 0x0020(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
	TArray<class FString>                         RequiredNames;                                     // 0x0030(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0040(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_CheckCurrentAnimationBPLibrary_CheckRibbonAnimation;

// Function RocoAnimExtension.ChineseToPinyinBPLibrary.ChineseToPinyinSampleFunction
// 0x0020 (0x0020 - 0x0000)
struct ChineseToPinyinBPLibrary_ChineseToPinyinSampleFunction final
{
public:
	class FString                                 fstr;                                              // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_ChineseToPinyinBPLibrary_ChineseToPinyinSampleFunction;

// Function RocoAnimExtension.ChineseToPinyinBPLibrary.IsChinese
// 0x0018 (0x0018 - 0x0000)
struct ChineseToPinyinBPLibrary_IsChinese final
{
public:
	class FString                                 str;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_ChineseToPinyinBPLibrary_IsChinese;

// Function RocoAnimExtension.GetCurAnimNameBPLibrary.GetCurAnimations
// 0x0018 (0x0018 - 0x0000)
struct GetCurAnimNameBPLibrary_GetCurAnimations final
{
public:
	class UAnimInstance*                          AnimInstance;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FString>                         OutNames;                                          // 0x0008(0x0010)(Parm, OutParm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_GetCurAnimNameBPLibrary_GetCurAnimations;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
