#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SAGCModule

#include "Basic.hpp"

#include "SAGCModule_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function SAGCModule.SAGCService.AppInit
// 0x000C (0x000C - 0x0000)
struct SAGCService_AppInit final
{
public:
	int32                                         Version;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TargetFPS;                                         // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SAGCService_AppInit;

// Function SAGCModule.SAGCService.BoostCPU
// 0x0008 (0x0008 - 0x0000)
struct SAGCService_BoostCPU final
{
public:
	int32                                         BoostPercent;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_BoostCPU;

// Function SAGCModule.SAGCService.BoostGPU
// 0x0008 (0x0008 - 0x0000)
struct SAGCService_BoostGPU final
{
public:
	int32                                         BoostPercent;                                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_BoostGPU;

// Function SAGCModule.SAGCService.GameStart
// 0x0001 (0x0001 - 0x0000)
struct SAGCService_GameStart final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_GameStart;

// Function SAGCModule.SAGCService.GameStop
// 0x0001 (0x0001 - 0x0000)
struct SAGCService_GameStop final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_GameStop;

// Function SAGCModule.SAGCService.GetCPUHeadroom
// 0x0010 (0x0010 - 0x0000)
struct SAGCService_GetCPUHeadroom final
{
public:
	int32                                         Type;                                              // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CoreOrClusterIndex;                                // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DurationSeconds;                                   // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x000C(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_GetCPUHeadroom;

// Function SAGCModule.SAGCService.GetGPUHeadroom
// 0x000C (0x000C - 0x0000)
struct SAGCService_GetGPUHeadroom final
{
public:
	int32                                         DurationSeconds;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAverage;                                          // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ReturnValue;                                       // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_GetGPUHeadroom;

// Function SAGCModule.SAGCService.GetPipelineThreadMaxNumber
// 0x0004 (0x0004 - 0x0000)
struct SAGCService_GetPipelineThreadMaxNumber final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_GetPipelineThreadMaxNumber;

// Function SAGCModule.SAGCService.HintHighCPUUtil
// 0x0008 (0x0008 - 0x0000)
struct SAGCService_HintHighCPUUtil final
{
public:
	int32                                         TID;                                               // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_HintHighCPUUtil;

// Function SAGCModule.SAGCService.HintLowCPUUtil
// 0x0008 (0x0008 - 0x0000)
struct SAGCService_HintLowCPUUtil final
{
public:
	int32                                         TID;                                               // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_HintLowCPUUtil;

// Function SAGCModule.SAGCService.HintLowLatency
// 0x0008 (0x0008 - 0x0000)
struct SAGCService_HintLowLatency final
{
public:
	int32                                         TID;                                               // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_HintLowLatency;

// Function SAGCModule.SAGCService.HintThreadPipeline
// 0x0018 (0x0018 - 0x0000)
struct SAGCService_HintThreadPipeline final
{
public:
	TArray<int32>                                 TIDs;                                              // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0010(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SAGCService_HintThreadPipeline;

// Function SAGCModule.SAGCService.InitGameConfig
// 0x0058 (0x0058 - 0x0000)
struct SAGCService_InitGameConfig final
{
public:
	TMap<ESAGCGameConfigID, int32>                Configs;                                           // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0050(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SAGCService_InitGameConfig;

// Function SAGCModule.SAGCService.QueryFrameStates
// 0x0028 (0x0028 - 0x0000)
struct SAGCService_QueryFrameStates final
{
public:
	struct FSAGCFrameState                        OutFrameState;                                     // 0x0000(0x0020)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SAGCService_QueryFrameStates;

// Function SAGCModule.SAGCService.QueryServiceConfig
// 0x0010 (0x0010 - 0x0000)
struct SAGCService_QueryServiceConfig final
{
public:
	struct FSAGCServiceConfig                     OutConfig;                                         // 0x0000(0x000C)(Parm, OutParm, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SAGCService_QueryServiceConfig;

// Function SAGCModule.SAGCService.QueryThermalHeadroomStatus
// 0x0004 (0x0004 - 0x0000)
struct SAGCService_QueryThermalHeadroomStatus final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_QueryThermalHeadroomStatus;

// Function SAGCModule.SAGCService.ReleaseThreadHints
// 0x000C (0x000C - 0x0000)
struct SAGCService_ReleaseThreadHints final
{
public:
	int32                                         Category;                                          // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TID;                                               // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_ReleaseThreadHints;

// Function SAGCModule.SAGCService.SetDesiredContentRate
// 0x0008 (0x0008 - 0x0000)
struct SAGCService_SetDesiredContentRate final
{
public:
	int32                                         FrameRateEnum;                                     // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_SetDesiredContentRate;

// Function SAGCModule.SAGCService.UpdateGameConfig
// 0x0058 (0x0058 - 0x0000)
struct SAGCService_UpdateGameConfig final
{
public:
	TMap<ESAGCGameConfigID, int32>                Configs;                                           // 0x0000(0x0050)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x0050(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_SAGCService_UpdateGameConfig;

// Function SAGCModule.SAGCService.GetPlatformName
// 0x0010 (0x0010 - 0x0000)
struct SAGCService_GetPlatformName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_GetPlatformName;

// Function SAGCModule.SAGCService.GetSDKVersion
// 0x0010 (0x0010 - 0x0000)
struct SAGCService_GetSDKVersion final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_GetSDKVersion;

// Function SAGCModule.SAGCService.IsGameRunning
// 0x0001 (0x0001 - 0x0000)
struct SAGCService_IsGameRunning final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_IsGameRunning;

// Function SAGCModule.SAGCService.IsInitialized
// 0x0001 (0x0001 - 0x0000)
struct SAGCService_IsInitialized final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_IsInitialized;

// Function SAGCModule.SAGCService.IsSDKLoaded
// 0x0001 (0x0001 - 0x0000)
struct SAGCService_IsSDKLoaded final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SAGCService_IsSDKLoaded;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
