#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SingletonManager

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function SingletonManager.SingletonManager.Get
// 0x0008 (0x0008 - 0x0000)
struct SingletonManager_Get final
{
public:
	class USingletonManager*                      ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SingletonManager_Get;

// Function SingletonManager.SingletonManager.CreateSingleton
// 0x0018 (0x0018 - 0x0000)
struct SingletonManager_CreateSingleton final
{
public:
	class UClass*                                 SingletonClass;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UWorld*                                 InWorld;                                           // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UObject*                                ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SingletonManager_CreateSingleton;

// Function SingletonManager.SingletonManager.GetOrCreateSingleton
// 0x0018 (0x0018 - 0x0000)
struct SingletonManager_GetOrCreateSingleton final
{
public:
	class UClass*                                 SingletonClass;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UWorld*                                 InWorld;                                           // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UObject*                                ReturnValue;                                       // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SingletonManager_GetOrCreateSingleton;

// Function SingletonManager.SingletonManager.GetSingleton
// 0x0010 (0x0010 - 0x0000)
struct SingletonManager_GetSingleton final
{
public:
	class UClass*                                 SingletonClass;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UObject*                                ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SingletonManager_GetSingleton;

// Function SingletonManager.SingletonManager.RemoveSingleton
// 0x0008 (0x0008 - 0x0000)
struct SingletonManager_RemoveSingleton final
{
public:
	class UClass*                                 SingletonClass;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SingletonManager_RemoveSingleton;

// Function SingletonManager.SingletonManager.SetSingleton
// 0x0010 (0x0010 - 0x0000)
struct SingletonManager_SetSingleton final
{
public:
	class UObject*                                Instance;                                          // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UClass*                                 SingletonClass;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_SingletonManager_SetSingleton;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
