#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SkeletalMeshMerger

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class SkeletalMeshMerger.AvatarAutoUVTransform
// 0x0008 (0x0030 - 0x0028)
class UAvatarAutoUVTransform final : public UObject
{
public:
	uint8                                         Pad_28[0x8];                                       // 0x0028(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AvatarAutoUVTransform")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AvatarAutoUVTransform")
	}
	static class UAvatarAutoUVTransform* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAvatarAutoUVTransform>();
	}
};
DUMPER7_ASSERTS_UAvatarAutoUVTransform;

// Class SkeletalMeshMerger.NRCTextureMergeMethodBase
// 0x0000 (0x0028 - 0x0028)
class UNRCTextureMergeMethodBase : public UObject
{
public:
	void GetTextureScreenPosAndSize(int32 TotalTexNum, int32 Index_0, const struct FTransform& UVTransform, const struct FVector2D& TextureSize, struct FVector2D* OutUVStart, struct FVector2D* OutUVEnd);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("NRCTextureMergeMethodBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NRCTextureMergeMethodBase")
	}
	static class UNRCTextureMergeMethodBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNRCTextureMergeMethodBase>();
	}
};
DUMPER7_ASSERTS_UNRCTextureMergeMethodBase;

// Class SkeletalMeshMerger.SkeletalMeshMergerBPLibrary
// 0x0000 (0x0028 - 0x0028)
class USkeletalMeshMergerBPLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void BakeSkeletalMesh(class USkeletalMesh* RuntimeSkeletalMesh, class USkeletalMesh* RefSkeletalMesh);
	static void CopyVirtualBone(class USkeleton* SrcSkeleton, class USkeleton* DstSkeleton);
	static class USkeletalMesh* MergeMeshes(const struct FSkeletalMeshMergeParams& Params_0);
	static class USkeletalMesh* NRCMergeMeshes(const struct FNRCSkeletalMeshMergeParams& Params_0);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("SkeletalMeshMergerBPLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SkeletalMeshMergerBPLibrary")
	}
	static class USkeletalMeshMergerBPLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<USkeletalMeshMergerBPLibrary>();
	}
};
DUMPER7_ASSERTS_USkeletalMeshMergerBPLibrary;

SDK_NAMESPACE_END
