#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_SleepingOwlSanctuary_Unlock

#include "Basic.hpp"

#include "UMG_SleepingOwlSanctuary_Unlock_classes.hpp"
#include "UMG_SleepingOwlSanctuary_Unlock_parameters.hpp"


SDK_NAMESPACE_START

// Function UMG_SleepingOwlSanctuary_Unlock.UMG_SleepingOwlSanctuary_Unlock_C.ExecuteUbergraph_UMG_SleepingOwlSanctuary_Unlock
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_SleepingOwlSanctuary_Unlock_C::ExecuteUbergraph_UMG_SleepingOwlSanctuary_Unlock(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SleepingOwlSanctuary_Unlock_C", "ExecuteUbergraph_UMG_SleepingOwlSanctuary_Unlock");

	Params::UMG_SleepingOwlSanctuary_Unlock_C_ExecuteUbergraph_UMG_SleepingOwlSanctuary_Unlock Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_SleepingOwlSanctuary_Unlock.UMG_SleepingOwlSanctuary_Unlock_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UUMG_SleepingOwlSanctuary_Unlock_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SleepingOwlSanctuary_Unlock_C", "PreConstruct");

	Params::UMG_SleepingOwlSanctuary_Unlock_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_SleepingOwlSanctuary_Unlock.UMG_SleepingOwlSanctuary_Unlock_C.SetMaterial
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UTexture2D*                       Texture                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_SleepingOwlSanctuary_Unlock_C::SetMaterial(class UTexture2D* Texture)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SleepingOwlSanctuary_Unlock_C", "SetMaterial");

	Params::UMG_SleepingOwlSanctuary_Unlock_C_SetMaterial Parms{};

	Parms.Texture = Texture;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_SleepingOwlSanctuary_Unlock.UMG_SleepingOwlSanctuary_Unlock_C.GetModuleName
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)

class FString UUMG_SleepingOwlSanctuary_Unlock_C::GetModuleName() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_SleepingOwlSanctuary_Unlock_C", "GetModuleName");

	Params::UMG_SleepingOwlSanctuary_Unlock_C_GetModuleName Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
