#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_TaskTips

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UMG_TaskTips.UMG_TaskTips_C.ExecuteUbergraph_UMG_TaskTips
// 0x0004 (0x0004 - 0x0000)
struct UMG_TaskTips_C_ExecuteUbergraph_UMG_TaskTips final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UMG_TaskTips_C_ExecuteUbergraph_UMG_TaskTips;

// Function UMG_TaskTips.UMG_TaskTips_C.GetModuleName
// 0x0010 (0x0010 - 0x0000)
struct UMG_TaskTips_C_GetModuleName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UMG_TaskTips_C_GetModuleName;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
