#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_CaptureBackground

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "TUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UMG_CaptureBackground.UMG_CaptureBackground_C
// 0x0028 (0x0658 - 0x0630)
class UUMG_CaptureBackground_C final : public UNRCCommonUmgProperty
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0630(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNRCBackgroundBlur*                     BackgroundBlur;                                    // 0x0638(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNRCImage*                              BackgroundCapture;                                 // 0x0640(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 NRCBackground_Noise;                               // 0x0648(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsCaptureTransparent;                              // 0x0650(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UMG_CaptureBackground(int32 EntryPoint);
	void SetGaussianBlurType(const bool IsShowCameraGaussianBlur, const bool IsShowNRCBackGroundNoise, const bool IsShowNRCBackGroundBlur);
	void PreConstruct(bool IsDesignTime);
	void SetMaterialIstance(class UTextureRenderTarget2D* Capture);

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UMG_CaptureBackground_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UMG_CaptureBackground_C")
	}
	static class UUMG_CaptureBackground_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUMG_CaptureBackground_C>();
	}
};
DUMPER7_ASSERTS_UUMG_CaptureBackground_C;

SDK_NAMESPACE_END
