#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_Tips

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "TUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass UMG_Tips.UMG_Tips_C
// 0x0030 (0x04C8 - 0x0498)
class UUMG_Tips_C final : public UNRCUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0498(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       TweenOut;                                          // 0x04A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       TweenIn;                                           // 0x04A8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas;                                            // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNxRichText*                            Text_Tips;                                         // 0x04C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UMG_Tips(int32 EntryPoint);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);

	class FString GetModuleName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("UMG_Tips_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"UMG_Tips_C")
	}
	static class UUMG_Tips_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUMG_Tips_C>();
	}
};
DUMPER7_ASSERTS_UUMG_Tips_C;

SDK_NAMESPACE_END
