#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_SleepingOwlSanctuary_Unlock

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UMG_SleepingOwlSanctuary_Unlock.UMG_SleepingOwlSanctuary_Unlock_C.ExecuteUbergraph_UMG_SleepingOwlSanctuary_Unlock
// 0x0018 (0x0018 - 0x0000)
struct UMG_SleepingOwlSanctuary_Unlock_C_ExecuteUbergraph_UMG_SleepingOwlSanctuary_Unlock final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UMG_SleepingOwlSanctuary_Unlock_C_ExecuteUbergraph_UMG_SleepingOwlSanctuary_Unlock;

// Function UMG_SleepingOwlSanctuary_Unlock.UMG_SleepingOwlSanctuary_Unlock_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UMG_SleepingOwlSanctuary_Unlock_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UMG_SleepingOwlSanctuary_Unlock_C_PreConstruct;

// Function UMG_SleepingOwlSanctuary_Unlock.UMG_SleepingOwlSanctuary_Unlock_C.SetMaterial
// 0x0008 (0x0008 - 0x0000)
struct UMG_SleepingOwlSanctuary_Unlock_C_SetMaterial final
{
public:
	class UTexture2D*                             Texture;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UMG_SleepingOwlSanctuary_Unlock_C_SetMaterial;

// Function UMG_SleepingOwlSanctuary_Unlock.UMG_SleepingOwlSanctuary_Unlock_C.GetModuleName
// 0x0010 (0x0010 - 0x0000)
struct UMG_SleepingOwlSanctuary_Unlock_C_GetModuleName final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UMG_SleepingOwlSanctuary_Unlock_C_GetModuleName;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
